/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.yapstone.apiuat.models.*;
import com.yapstone.apiuat.exceptions.*;
import com.yapstone.apiuat.APIHelper;
import com.yapstone.apiuat.DateTimeHelper;
import com.yapstone.apiuat.Configuration;
import com.yapstone.apiuat.testing.TestHelper;
import com.yapstone.apiuat.controllers.ContractsController;

import com.fasterxml.jackson.core.type.TypeReference;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

public class ContractsControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static ContractsController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getContracts();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Retrieves all of the Contracts
     * @throws Throwable
     */
    @Test
    public void testTestGetAllContracts() throws Throwable {
        // Parameters for the API call
        String applicantId = null;
        String assetId = null;
        String payoutInstrumentId = null;
        Product1Enum product = null;
        Integer offset = 0;
        Integer limit = 1000;

        // Set callback and perform API call
        ContractResourceDTO result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getAllContracts(applicantId, assetId, payoutInstrumentId, product, offset, limit);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders(), true));

    }

}
