/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.yapstone.apiuat.models.*;
import com.yapstone.apiuat.exceptions.*;
import com.yapstone.apiuat.APIHelper;
import com.yapstone.apiuat.DateTimeHelper;
import com.yapstone.apiuat.Configuration;
import com.yapstone.apiuat.testing.TestHelper;
import com.yapstone.apiuat.controllers.InstrumentsController;

import com.fasterxml.jackson.core.type.TypeReference;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

public class InstrumentsControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static InstrumentsController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getInstruments();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Get all Payout Instrument Resources the actor has access to in the system.
     * @throws Throwable
     */
    @Test
    public void testTestGetInstruments() throws Throwable {
        // Parameters for the API call
        Integer page = null;
        Integer size = null;

        // Set callback and perform API call
        PayoutInstrumentsResource result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getInstruments(page, size);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders(), true));

    }

}
