/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;

import com.yapstone.apiuat.*;
import com.yapstone.apiuat.models.*;
import com.yapstone.apiuat.exceptions.*;
import com.yapstone.apiuat.http.client.HttpClient;
import com.yapstone.apiuat.http.client.HttpContext;
import com.yapstone.apiuat.http.request.HttpRequest;
import com.yapstone.apiuat.http.response.HttpResponse;
import com.yapstone.apiuat.http.response.HttpStringResponse;
import com.yapstone.apiuat.http.client.APICallBack;
import com.yapstone.apiuat.controllers.syncwrapper.APICallBackCatcher;

public class IndividualApplicantsController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static IndividualApplicantsController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the IndividualApplicantsController class 
     */
    public static IndividualApplicantsController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new IndividualApplicantsController();
                }
            }
        }
        return instance;
    }

    /**
     * Get all Individual Applicant Resources the actor has access to in the system.
     * @param    externalId    Required parameter: The identifier used by an external client.
     * @param    page    Optional parameter: page number
     * @param    size    Optional parameter: Maximum number of records to return per page
     * @return    Returns the IndividualApplicantsResource response from the API call 
     */
    public IndividualApplicantsResource getIndividualApplicants(
                final String externalId,
                final Integer page,
                final Integer size
    ) throws Throwable {

        HttpRequest _request = _buildGetIndividualApplicantsRequest(externalId, page, size);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetIndividualApplicantsResponse(_context);
    }

    /**
     * Get all Individual Applicant Resources the actor has access to in the system.
     * @param    externalId    Required parameter: The identifier used by an external client.
     * @param    page    Optional parameter: page number
     * @param    size    Optional parameter: Maximum number of records to return per page
     */
    public void getIndividualApplicantsAsync(
                final String externalId,
                final Integer page,
                final Integer size,
                final APICallBack<IndividualApplicantsResource> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetIndividualApplicantsRequest(externalId, page, size);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            IndividualApplicantsResource returnValue = _handleGetIndividualApplicantsResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getIndividualApplicants
     */
    private HttpRequest _buildGetIndividualApplicantsRequest(
                final String externalId,
                final Integer page,
                final Integer size) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/individual-applicants");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("externalId", externalId);
        if (page != null) {
            _queryParameters.put("page", page);
        }
        if (size != null) {
            _queryParameters.put("size", size);
        }
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getIndividualApplicants
     * @return An object of type IndividualApplicantsResource
     */
    private IndividualApplicantsResource _handleGetIndividualApplicantsResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 422) {
            throw new APIException("unprocessable", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        IndividualApplicantsResource _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<IndividualApplicantsResource>(){});

        return _result;
    }

    /**
     * Creates an Applicant Resource in the system.
     * @param    body    Required parameter: The Applicant Resource to be created.
     * @param    xYapstoneFpsid    Optional parameter: Example: 
     * @return    Returns the IndividualApplicantResource response from the API call 
     */
    public IndividualApplicantResource createIndividualApplicant(
                final IndividualApplicantRequest body,
                final String xYapstoneFpsid
    ) throws Throwable {

        HttpRequest _request = _buildCreateIndividualApplicantRequest(body, xYapstoneFpsid);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleCreateIndividualApplicantResponse(_context);
    }

    /**
     * Creates an Applicant Resource in the system.
     * @param    body    Required parameter: The Applicant Resource to be created.
     * @param    xYapstoneFpsid    Optional parameter: Example: 
     */
    public void createIndividualApplicantAsync(
                final IndividualApplicantRequest body,
                final String xYapstoneFpsid,
                final APICallBack<IndividualApplicantResource> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildCreateIndividualApplicantRequest(body, xYapstoneFpsid);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            IndividualApplicantResource returnValue = _handleCreateIndividualApplicantResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for createIndividualApplicant
     */
    private HttpRequest _buildCreateIndividualApplicantRequest(
                final IndividualApplicantRequest body,
                final String xYapstoneFpsid) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/individual-applicants");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        if (xYapstoneFpsid != null) {
            _headers.put("x-yapstone-fpsid", xYapstoneFpsid);
        }
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");
        _headers.put("content-type", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().postBody(_queryUrl, _headers, APIHelper.serialize(body));

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for createIndividualApplicant
     * @return An object of type IndividualApplicantResource
     */
    private IndividualApplicantResource _handleCreateIndividualApplicantResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 422) {
            throw new APIException("unprocessable entity", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        IndividualApplicantResource _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<IndividualApplicantResource>(){});

        return _result;
    }

    /**
     * Deactivates the Individual Applicant Resource in the system.
     * @param    applicantId    Required parameter: The unique id of the Individual Applicant Resource.
     * @return    Returns the DeactivateResponse response from the API call 
     */
    public DeactivateResponse deleteDeactivateApplicant(
                final String applicantId
    ) throws Throwable {

        HttpRequest _request = _buildDeleteDeactivateApplicantRequest(applicantId);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleDeleteDeactivateApplicantResponse(_context);
    }

    /**
     * Deactivates the Individual Applicant Resource in the system.
     * @param    applicantId    Required parameter: The unique id of the Individual Applicant Resource.
     */
    public void deleteDeactivateApplicantAsync(
                final String applicantId,
                final APICallBack<DeactivateResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildDeleteDeactivateApplicantRequest(applicantId);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            DeactivateResponse returnValue = _handleDeleteDeactivateApplicantResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for deleteDeactivateApplicant
     */
    private HttpRequest _buildDeleteDeactivateApplicantRequest(
                final String applicantId) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/individual-applicants/{applicantId}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("applicantId", applicantId);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().delete(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for deleteDeactivateApplicant
     * @return An object of type DeactivateResponse
     */
    private DeactivateResponse _handleDeleteDeactivateApplicantResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("not found", _context);
        }
        if (_responseCode == 422) {
            throw new APIException("unprocessable entity", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        DeactivateResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<DeactivateResponse>(){});

        return _result;
    }

    /**
     * Updates the Individual Applicant Resource.
     * @param    applicantId    Required parameter: The unique id of the Individual Applicant Resource.
     * @param    body    Required parameter: The Applicant Request Resource to be updated.
     * @param    xYapstoneFpsid    Optional parameter: Example: 
     * @return    Returns the IndividualApplicantResource response from the API call 
     */
    public IndividualApplicantResource updateIndividualApplicant(
                final String applicantId,
                final IndividualApplicantUpdateRequest body,
                final String xYapstoneFpsid
    ) throws Throwable {

        HttpRequest _request = _buildUpdateIndividualApplicantRequest(applicantId, body, xYapstoneFpsid);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleUpdateIndividualApplicantResponse(_context);
    }

    /**
     * Updates the Individual Applicant Resource.
     * @param    applicantId    Required parameter: The unique id of the Individual Applicant Resource.
     * @param    body    Required parameter: The Applicant Request Resource to be updated.
     * @param    xYapstoneFpsid    Optional parameter: Example: 
     */
    public void updateIndividualApplicantAsync(
                final String applicantId,
                final IndividualApplicantUpdateRequest body,
                final String xYapstoneFpsid,
                final APICallBack<IndividualApplicantResource> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildUpdateIndividualApplicantRequest(applicantId, body, xYapstoneFpsid);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            IndividualApplicantResource returnValue = _handleUpdateIndividualApplicantResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for updateIndividualApplicant
     */
    private HttpRequest _buildUpdateIndividualApplicantRequest(
                final String applicantId,
                final IndividualApplicantUpdateRequest body,
                final String xYapstoneFpsid) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/individual-applicants/{applicantId}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("applicantId", applicantId);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        if (xYapstoneFpsid != null) {
            _headers.put("x-yapstone-fpsid", xYapstoneFpsid);
        }
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");
        _headers.put("content-type", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().putBody(_queryUrl, _headers, APIHelper.serialize(body));

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for updateIndividualApplicant
     * @return An object of type IndividualApplicantResource
     */
    private IndividualApplicantResource _handleUpdateIndividualApplicantResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("not found", _context);
        }
        if (_responseCode == 422) {
            throw new APIException("unprocessable entity", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        IndividualApplicantResource _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<IndividualApplicantResource>(){});

        return _result;
    }

    /**
     * Retrieves an Individual Applicant Resource from the system for the given applicantId.
     * @param    applicantId    Required parameter: The unique id of the Individual Applicant Resource.
     * @return    Returns the IndividualApplicantResource response from the API call 
     */
    public IndividualApplicantResource getIndividualApplicant(
                final String applicantId
    ) throws Throwable {

        HttpRequest _request = _buildGetIndividualApplicantRequest(applicantId);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetIndividualApplicantResponse(_context);
    }

    /**
     * Retrieves an Individual Applicant Resource from the system for the given applicantId.
     * @param    applicantId    Required parameter: The unique id of the Individual Applicant Resource.
     */
    public void getIndividualApplicantAsync(
                final String applicantId,
                final APICallBack<IndividualApplicantResource> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetIndividualApplicantRequest(applicantId);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            IndividualApplicantResource returnValue = _handleGetIndividualApplicantResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getIndividualApplicant
     */
    private HttpRequest _buildGetIndividualApplicantRequest(
                final String applicantId) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/individual-applicants/{applicantId}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("applicantId", applicantId);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getIndividualApplicant
     * @return An object of type IndividualApplicantResource
     */
    private IndividualApplicantResource _handleGetIndividualApplicantResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("not found", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        IndividualApplicantResource _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<IndividualApplicantResource>(){});

        return _result;
    }

}
