/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;

import com.yapstone.apiuat.*;
import com.yapstone.apiuat.models.*;
import com.yapstone.apiuat.exceptions.*;
import com.yapstone.apiuat.http.client.HttpClient;
import com.yapstone.apiuat.http.client.HttpContext;
import com.yapstone.apiuat.http.request.HttpRequest;
import com.yapstone.apiuat.http.response.HttpResponse;
import com.yapstone.apiuat.http.response.HttpStringResponse;
import com.yapstone.apiuat.http.client.APICallBack;
import com.yapstone.apiuat.controllers.syncwrapper.APICallBackCatcher;

public class PayoutInstrumentsController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static PayoutInstrumentsController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the PayoutInstrumentsController class 
     */
    public static PayoutInstrumentsController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new PayoutInstrumentsController();
                }
            }
        }
        return instance;
    }

    /**
     * Get all Payout Instrument Resources the actor has access to in the system.
     * @param    page    Optional parameter: page number
     * @param    size    Optional parameter: Maximum number of records to return per page
     * @return    Returns the PayoutInstrumentsResource response from the API call 
     */
    public PayoutInstrumentsResource getPayoutInstruments(
                final Integer page,
                final Integer size
    ) throws Throwable {

        HttpRequest _request = _buildGetPayoutInstrumentsRequest(page, size);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetPayoutInstrumentsResponse(_context);
    }

    /**
     * Get all Payout Instrument Resources the actor has access to in the system.
     * @param    page    Optional parameter: page number
     * @param    size    Optional parameter: Maximum number of records to return per page
     */
    public void getPayoutInstrumentsAsync(
                final Integer page,
                final Integer size,
                final APICallBack<PayoutInstrumentsResource> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetPayoutInstrumentsRequest(page, size);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            PayoutInstrumentsResource returnValue = _handleGetPayoutInstrumentsResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getPayoutInstruments
     */
    private HttpRequest _buildGetPayoutInstrumentsRequest(
                final Integer page,
                final Integer size) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/payout-instruments");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        if (page != null) {
            _queryParameters.put("page", page);
        }
        if (size != null) {
            _queryParameters.put("size", size);
        }
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getPayoutInstruments
     * @return An object of type PayoutInstrumentsResource
     */
    private PayoutInstrumentsResource _handleGetPayoutInstrumentsResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 422) {
            throw new APIException("unprocessable", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        PayoutInstrumentsResource _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<PayoutInstrumentsResource>(){});

        return _result;
    }

    /**
     * Creates an Payout Instrument Resource in the system.
     * @param    body    Required parameter: The Payout Instrument Request Resource to be created.
     * @param    xYapstoneFpsid    Optional parameter: Example: 
     * @return    Returns the PayoutInstrumentResource response from the API call 
     */
    public PayoutInstrumentResource createPayoutInstrument(
                final PayoutInstrumentRequest body,
                final String xYapstoneFpsid
    ) throws Throwable {

        HttpRequest _request = _buildCreatePayoutInstrumentRequest(body, xYapstoneFpsid);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleCreatePayoutInstrumentResponse(_context);
    }

    /**
     * Creates an Payout Instrument Resource in the system.
     * @param    body    Required parameter: The Payout Instrument Request Resource to be created.
     * @param    xYapstoneFpsid    Optional parameter: Example: 
     */
    public void createPayoutInstrumentAsync(
                final PayoutInstrumentRequest body,
                final String xYapstoneFpsid,
                final APICallBack<PayoutInstrumentResource> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildCreatePayoutInstrumentRequest(body, xYapstoneFpsid);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            PayoutInstrumentResource returnValue = _handleCreatePayoutInstrumentResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for createPayoutInstrument
     */
    private HttpRequest _buildCreatePayoutInstrumentRequest(
                final PayoutInstrumentRequest body,
                final String xYapstoneFpsid) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/payout-instruments");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        if (xYapstoneFpsid != null) {
            _headers.put("x-yapstone-fpsid", xYapstoneFpsid);
        }
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");
        _headers.put("content-type", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().postBody(_queryUrl, _headers, APIHelper.serialize(body));

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for createPayoutInstrument
     * @return An object of type PayoutInstrumentResource
     */
    private PayoutInstrumentResource _handleCreatePayoutInstrumentResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 422) {
            throw new APIException("unprocessable entity", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        PayoutInstrumentResource _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<PayoutInstrumentResource>(){});

        return _result;
    }

    /**
     * Retrieves an Payout Instrument Resource from the system for the given payoutInstrumentId.
     * @param    payoutInstrumentId    Required parameter: The unique id of the  Payout Instrument Resource.
     * @return    Returns the PayoutInstrumentResource response from the API call 
     */
    public PayoutInstrumentResource getPayoutInstrument(
                final String payoutInstrumentId
    ) throws Throwable {

        HttpRequest _request = _buildGetPayoutInstrumentRequest(payoutInstrumentId);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetPayoutInstrumentResponse(_context);
    }

    /**
     * Retrieves an Payout Instrument Resource from the system for the given payoutInstrumentId.
     * @param    payoutInstrumentId    Required parameter: The unique id of the  Payout Instrument Resource.
     */
    public void getPayoutInstrumentAsync(
                final String payoutInstrumentId,
                final APICallBack<PayoutInstrumentResource> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetPayoutInstrumentRequest(payoutInstrumentId);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            PayoutInstrumentResource returnValue = _handleGetPayoutInstrumentResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getPayoutInstrument
     */
    private HttpRequest _buildGetPayoutInstrumentRequest(
                final String payoutInstrumentId) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/payout-instruments/{payoutInstrumentId}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("payoutInstrumentId", payoutInstrumentId);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getPayoutInstrument
     * @return An object of type PayoutInstrumentResource
     */
    private PayoutInstrumentResource _handleGetPayoutInstrumentResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("not found", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        PayoutInstrumentResource _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<PayoutInstrumentResource>(){});

        return _result;
    }

    /**
     * Updates the PayoutInstrument Resource.
     * @param    payoutInstrumentId    Required parameter: The unique id of the  Payout Instrument Resource.
     * @param    body    Required parameter: The PayoutInstrument Request Resource to be updated.
     * @param    xYapstoneFpsid    Optional parameter: Example: 
     * @return    Returns the PayoutInstrumentResource response from the API call 
     */
    public PayoutInstrumentResource updatePayoutInstrument(
                final String payoutInstrumentId,
                final PayoutInstrumentUpdateRequest body,
                final String xYapstoneFpsid
    ) throws Throwable {

        HttpRequest _request = _buildUpdatePayoutInstrumentRequest(payoutInstrumentId, body, xYapstoneFpsid);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleUpdatePayoutInstrumentResponse(_context);
    }

    /**
     * Updates the PayoutInstrument Resource.
     * @param    payoutInstrumentId    Required parameter: The unique id of the  Payout Instrument Resource.
     * @param    body    Required parameter: The PayoutInstrument Request Resource to be updated.
     * @param    xYapstoneFpsid    Optional parameter: Example: 
     */
    public void updatePayoutInstrumentAsync(
                final String payoutInstrumentId,
                final PayoutInstrumentUpdateRequest body,
                final String xYapstoneFpsid,
                final APICallBack<PayoutInstrumentResource> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildUpdatePayoutInstrumentRequest(payoutInstrumentId, body, xYapstoneFpsid);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            PayoutInstrumentResource returnValue = _handleUpdatePayoutInstrumentResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for updatePayoutInstrument
     */
    private HttpRequest _buildUpdatePayoutInstrumentRequest(
                final String payoutInstrumentId,
                final PayoutInstrumentUpdateRequest body,
                final String xYapstoneFpsid) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/payout-instruments/{payoutInstrumentId}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("payoutInstrumentId", payoutInstrumentId);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        if (xYapstoneFpsid != null) {
            _headers.put("x-yapstone-fpsid", xYapstoneFpsid);
        }
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");
        _headers.put("content-type", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().putBody(_queryUrl, _headers, APIHelper.serialize(body));

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for updatePayoutInstrument
     * @return An object of type PayoutInstrumentResource
     */
    private PayoutInstrumentResource _handleUpdatePayoutInstrumentResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("not found", _context);
        }
        if (_responseCode == 422) {
            throw new APIException("unprocessable entity", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        PayoutInstrumentResource _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<PayoutInstrumentResource>(){});

        return _result;
    }

    /**
     * Deactivates the Payout Instrument Resource in the system.
     * @param    payoutInstrumentId    Required parameter: The unique id of the  Payout Instrument Resource.
     * @return    Returns the DeactivateResponse response from the API call 
     */
    public DeactivateResponse deleteDeactivatePayoutInstrument(
                final String payoutInstrumentId
    ) throws Throwable {

        HttpRequest _request = _buildDeleteDeactivatePayoutInstrumentRequest(payoutInstrumentId);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleDeleteDeactivatePayoutInstrumentResponse(_context);
    }

    /**
     * Deactivates the Payout Instrument Resource in the system.
     * @param    payoutInstrumentId    Required parameter: The unique id of the  Payout Instrument Resource.
     */
    public void deleteDeactivatePayoutInstrumentAsync(
                final String payoutInstrumentId,
                final APICallBack<DeactivateResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildDeleteDeactivatePayoutInstrumentRequest(payoutInstrumentId);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            DeactivateResponse returnValue = _handleDeleteDeactivatePayoutInstrumentResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for deleteDeactivatePayoutInstrument
     */
    private HttpRequest _buildDeleteDeactivatePayoutInstrumentRequest(
                final String payoutInstrumentId) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/payout-instruments/{payoutInstrumentId}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("payoutInstrumentId", payoutInstrumentId);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("Authorization", Configuration.authorization);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().delete(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for deleteDeactivatePayoutInstrument
     * @return An object of type DeactivateResponse
     */
    private DeactivateResponse _handleDeleteDeactivatePayoutInstrumentResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("unauthorized", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("not found", _context);
        }
        if (_responseCode == 422) {
            throw new APIException("unprocessable entity", _context);
        }
        if (_responseCode == 500) {
            throw new APIException("internal service error", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        DeactivateResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<DeactivateResponse>(){});

        return _result;
    }

}
