/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class AbstractEntityBuilder {
    //the instance to build
    private AbstractEntity abstractEntity;

    /**
     * Default constructor to initialize the instance
     */
    public AbstractEntityBuilder() {
        abstractEntity = new AbstractEntity();
    }

    /**
     * The partners externalId id for entity.
     */
    public AbstractEntityBuilder externalId(String externalId) {
        abstractEntity.setExternalId(externalId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AbstractEntity build() {
        return abstractEntity;
    }
}