/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class ActionStatusResourceBuilder {
    //the instance to build
    private ActionStatusResource actionStatusResource;

    /**
     * Default constructor to initialize the instance
     */
    public ActionStatusResourceBuilder() {
        actionStatusResource = new ActionStatusResource();
    }

    /**
     * The status of the entity.
     */
    public ActionStatusResourceBuilder status(StatusEnum status) {
        actionStatusResource.setStatus(status);
        return this;
    }

    public ActionStatusResourceBuilder requiredActions(List<ActionResource> requiredActions) {
        actionStatusResource.setRequiredActions(requiredActions);
        return this;
    }

    /**
     * Indicates the reason for suspension
     */
    public ActionStatusResourceBuilder suspendedReasons(List<SuspensionReasonResource> suspendedReasons) {
        actionStatusResource.setSuspendedReasons(suspendedReasons);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ActionStatusResource build() {
        return actionStatusResource;
    }
}