/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class AddressResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5905418775373386225L;
    private String street1;
    private String street2;
    private String street3;
    private String street4;
    private String city;
    private String state;
    private String postalCode;
    private String countryCode;
    /** GETTER
     * The street address line 1.
     */
    @JsonGetter("street1")
    public String getStreet1 ( ) { 
        return this.street1;
    }
    
    /** SETTER
     * The street address line 1.
     */
    @JsonSetter("street1")
    public void setStreet1 (String value) { 
        this.street1 = value;
    }
 
    /** GETTER
     * The street address line 2.
     */
    @JsonGetter("street2")
    public String getStreet2 ( ) { 
        return this.street2;
    }
    
    /** SETTER
     * The street address line 2.
     */
    @JsonSetter("street2")
    public void setStreet2 (String value) { 
        this.street2 = value;
    }
 
    /** GETTER
     * The street address line 3.
     */
    @JsonGetter("street3")
    public String getStreet3 ( ) { 
        return this.street3;
    }
    
    /** SETTER
     * The street address line 3.
     */
    @JsonSetter("street3")
    public void setStreet3 (String value) { 
        this.street3 = value;
    }
 
    /** GETTER
     * The street address line 4.
     */
    @JsonGetter("street4")
    public String getStreet4 ( ) { 
        return this.street4;
    }
    
    /** SETTER
     * The street address line 4.
     */
    @JsonSetter("street4")
    public void setStreet4 (String value) { 
        this.street4 = value;
    }
 
    /** GETTER
     * The name of the city.
     */
    @JsonGetter("city")
    public String getCity ( ) { 
        return this.city;
    }
    
    /** SETTER
     * The name of the city.
     */
    @JsonSetter("city")
    public void setCity (String value) { 
        this.city = value;
    }
 
    /** GETTER
     * The state or province where the address resides(required for USA and CAN).
     */
    @JsonGetter("state")
    public String getState ( ) { 
        return this.state;
    }
    
    /** SETTER
     * The state or province where the address resides(required for USA and CAN).
     */
    @JsonSetter("state")
    public void setState (String value) { 
        this.state = value;
    }
 
    /** GETTER
     * The postal code of the address.
     */
    @JsonGetter("postalCode")
    public String getPostalCode ( ) { 
        return this.postalCode;
    }
    
    /** SETTER
     * The postal code of the address.
     */
    @JsonSetter("postalCode")
    public void setPostalCode (String value) { 
        this.postalCode = value;
    }
 
    /** GETTER
     * The 3-letter countryCode of the address.
     */
    @JsonGetter("countryCode")
    public String getCountryCode ( ) { 
        return this.countryCode;
    }
    
    /** SETTER
     * The 3-letter countryCode of the address.
     */
    @JsonSetter("countryCode")
    public void setCountryCode (String value) { 
        this.countryCode = value;
    }
 
}
