/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ApplicantOperationalStatus 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4091250689969374705L;
    private ActionStatusResource chargesStatus;
    private ActionStatusResource refundStatus;
    private ActionStatusResource creditStatus;
    /** GETTER
     * The status of the entity.
     */
    @JsonGetter("chargesStatus")
    public ActionStatusResource getChargesStatus ( ) { 
        return this.chargesStatus;
    }
    
    /** SETTER
     * The status of the entity.
     */
    @JsonSetter("chargesStatus")
    public void setChargesStatus (ActionStatusResource value) { 
        this.chargesStatus = value;
    }
 
    /** GETTER
     * The status of the entity.
     */
    @JsonGetter("refundStatus")
    public ActionStatusResource getRefundStatus ( ) { 
        return this.refundStatus;
    }
    
    /** SETTER
     * The status of the entity.
     */
    @JsonSetter("refundStatus")
    public void setRefundStatus (ActionStatusResource value) { 
        this.refundStatus = value;
    }
 
    /** GETTER
     * The status of the entity.
     */
    @JsonGetter("creditStatus")
    public ActionStatusResource getCreditStatus ( ) { 
        return this.creditStatus;
    }
    
    /** SETTER
     * The status of the entity.
     */
    @JsonSetter("creditStatus")
    public void setCreditStatus (ActionStatusResource value) { 
        this.creditStatus = value;
    }
 
}
