/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class ApplicantConsentRequestBuilder {
    //the instance to build
    private ApplicantConsentRequest applicantConsentRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApplicantConsentRequestBuilder() {
        applicantConsentRequest = new ApplicantConsentRequest();
    }

    public ApplicantConsentRequestBuilder type(ApplicantConsentTypeEnum type) {
        applicantConsentRequest.setType(type);
        return this;
    }

    /**
     * The version of the consent if there is one.
     */
    public ApplicantConsentRequestBuilder version(int version) {
        applicantConsentRequest.setVersion(version);
        return this;
    }

    /**
     * Indicates the acceptance of the T&Cs.
     */
    public ApplicantConsentRequestBuilder accepted(boolean accepted) {
        applicantConsentRequest.setAccepted(accepted);
        return this;
    }

    /**
     * The ipAddress origin of the incoming call.
     */
    public ApplicantConsentRequestBuilder ipAddress(String ipAddress) {
        applicantConsentRequest.setIpAddress(ipAddress);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApplicantConsentRequest build() {
        return applicantConsentRequest;
    }
}