/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class ApplicantOperationalStatusBuilder {
    //the instance to build
    private ApplicantOperationalStatus applicantOperationalStatus;

    /**
     * Default constructor to initialize the instance
     */
    public ApplicantOperationalStatusBuilder() {
        applicantOperationalStatus = new ApplicantOperationalStatus();
    }

    /**
     * The status of the entity.
     */
    public ApplicantOperationalStatusBuilder chargesStatus(ActionStatusResource chargesStatus) {
        applicantOperationalStatus.setChargesStatus(chargesStatus);
        return this;
    }

    /**
     * The status of the entity.
     */
    public ApplicantOperationalStatusBuilder refundStatus(ActionStatusResource refundStatus) {
        applicantOperationalStatus.setRefundStatus(refundStatus);
        return this;
    }

    /**
     * The status of the entity.
     */
    public ApplicantOperationalStatusBuilder creditStatus(ActionStatusResource creditStatus) {
        applicantOperationalStatus.setCreditStatus(creditStatus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApplicantOperationalStatus build() {
        return applicantOperationalStatus;
    }
}