/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class BankAccountDataResourceBuilder {
    //the instance to build
    private BankAccountDataResource bankAccountDataResource;

    /**
     * Default constructor to initialize the instance
     */
    public BankAccountDataResourceBuilder() {
        bankAccountDataResource = new BankAccountDataResource();
    }

    /**
     * The key to the vault that contains the sensitive bank data.
     */
    public BankAccountDataResourceBuilder bankAccountDataToken(String bankAccountDataToken) {
        bankAccountDataResource.setBankAccountDataToken(bankAccountDataToken);
        return this;
    }

    /**
     * routing code for USA, bank/branch identification for rest of the world
     */
    public BankAccountDataResourceBuilder routingCode(String routingCode) {
        bankAccountDataResource.setRoutingCode(routingCode);
        return this;
    }

    /**
     * Bank account number. If this is iban, routing code (bank/branch identification code) can be empty
     */
    public BankAccountDataResourceBuilder accountNumber(String accountNumber) {
        bankAccountDataResource.setAccountNumber(accountNumber);
        return this;
    }

    /**
     * The textual description of the account.
     */
    public BankAccountDataResourceBuilder displayText(String displayText) {
        bankAccountDataResource.setDisplayText(displayText);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BankAccountDataResource build() {
        return bankAccountDataResource;
    }
}