/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class BankAccountResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = -7163823882317143110L;
    private Type1Enum type;
    private String nameOnAccount;
    private String currency;
    private BankAccountDataResource bankAccountData;
    private String bankName;
    private String country;
    /** GETTER
     * The type of bank account [CHECKING, SAVINGS]
     */
    @JsonGetter("type")
    public Type1Enum getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The type of bank account [CHECKING, SAVINGS]
     */
    @JsonSetter("type")
    public void setType (Type1Enum value) { 
        this.type = value;
    }
 
    /** GETTER
     * The name on the account.
     */
    @JsonGetter("nameOnAccount")
    public String getNameOnAccount ( ) { 
        return this.nameOnAccount;
    }
    
    /** SETTER
     * The name on the account.
     */
    @JsonSetter("nameOnAccount")
    public void setNameOnAccount (String value) { 
        this.nameOnAccount = value;
    }
 
    /** GETTER
     * Need to be 3 digit currency code(ISO 3). USD, CAD, EUR, GBP, DOP, BSD, CRC, ANG, JMD, MXN, CHF.
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * Need to be 3 digit currency code(ISO 3). USD, CAD, EUR, GBP, DOP, BSD, CRC, ANG, JMD, MXN, CHF.
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
    /** GETTER
     * Detailed information about the bank account.
     */
    @JsonGetter("bankAccountData")
    public BankAccountDataResource getBankAccountData ( ) { 
        return this.bankAccountData;
    }
    
    /** SETTER
     * Detailed information about the bank account.
     */
    @JsonSetter("bankAccountData")
    public void setBankAccountData (BankAccountDataResource value) { 
        this.bankAccountData = value;
    }
 
    /** GETTER
     * The bank name.
     */
    @JsonGetter("bankName")
    public String getBankName ( ) { 
        return this.bankName;
    }
    
    /** SETTER
     * The bank name.
     */
    @JsonSetter("bankName")
    public void setBankName (String value) { 
        this.bankName = value;
    }
 
    /** GETTER
     * The bank country.
     */
    @JsonGetter("country")
    public String getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * The bank country.
     */
    @JsonSetter("country")
    public void setCountry (String value) { 
        this.country = value;
    }
 
}
