/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class BeneficialOwnersPatch 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8716406247681083673L;
    private PatchOperationEnum op;
    private String beneficialOwnerId;
    private BeneficialOwnerRequest beneficialOwnerEntity;
    /** GETTER
     * The operation to be performed
     */
    @JsonGetter("op")
    public PatchOperationEnum getOp ( ) { 
        return this.op;
    }
    
    /** SETTER
     * The operation to be performed
     */
    @JsonSetter("op")
    public void setOp (PatchOperationEnum value) { 
        this.op = value;
    }
 
    /** GETTER
     * The identifier for the entity.
     */
    @JsonGetter("beneficialOwnerId")
    public String getBeneficialOwnerId ( ) { 
        return this.beneficialOwnerId;
    }
    
    /** SETTER
     * The identifier for the entity.
     */
    @JsonSetter("beneficialOwnerId")
    public void setBeneficialOwnerId (String value) { 
        this.beneficialOwnerId = value;
    }
 
    /** GETTER
     * Beneficial Owner Request
     */
    @JsonGetter("beneficialOwnerEntity")
    public BeneficialOwnerRequest getBeneficialOwnerEntity ( ) { 
        return this.beneficialOwnerEntity;
    }
    
    /** SETTER
     * Beneficial Owner Request
     */
    @JsonSetter("beneficialOwnerEntity")
    public void setBeneficialOwnerEntity (BeneficialOwnerRequest value) { 
        this.beneficialOwnerEntity = value;
    }
 
}
