/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yapstone.apiuat.DateTimeHelper;
import org.joda.time.LocalDate;

@JsonInclude(Include.ALWAYS)
public class BeneficialOwnerResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5725845838703435610L;
    private String id;
    private EntityProductStatusResource status;
    private String externalId;
    private NameResource name;
    private AddressResource address;
    private String email;
    private GovIdentificationResource govIdentification;
    private LocalDate dateOfBirth;
    /** GETTER
     * The resource identifier for the Beneficial Owner
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * The resource identifier for the Beneficial Owner
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * The status of the entity.
     */
    @JsonGetter("status")
    public EntityProductStatusResource getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The status of the entity.
     */
    @JsonSetter("status")
    public void setStatus (EntityProductStatusResource value) { 
        this.status = value;
    }
 
    /** GETTER
     * The Mktplaces unique identifier for the Beneficial Owner.
     */
    @JsonGetter("externalId")
    public String getExternalId ( ) { 
        return this.externalId;
    }
    
    /** SETTER
     * The Mktplaces unique identifier for the Beneficial Owner.
     */
    @JsonSetter("externalId")
    public void setExternalId (String value) { 
        this.externalId = value;
    }
 
    /** GETTER
     * The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix.
     */
    @JsonGetter("name")
    public NameResource getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix.
     */
    @JsonSetter("name")
    public void setName (NameResource value) { 
        this.name = value;
    }
 
    /** GETTER
     * The address of the application, asset, bank, etc.
     */
    @JsonGetter("address")
    public AddressResource getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * The address of the application, asset, bank, etc.
     */
    @JsonSetter("address")
    public void setAddress (AddressResource value) { 
        this.address = value;
    }
 
    /** GETTER
     * The email address.
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * The email address.
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
    /** GETTER
     * The goverment identification information.For US - Need Last4 SSN.
     */
    @JsonGetter("govIdentification")
    public GovIdentificationResource getGovIdentification ( ) { 
        return this.govIdentification;
    }
    
    /** SETTER
     * The goverment identification information.For US - Need Last4 SSN.
     */
    @JsonSetter("govIdentification")
    public void setGovIdentification (GovIdentificationResource value) { 
        this.govIdentification = value;
    }
 
    /** GETTER
     * The date of birth for the person.
     */
    @JsonGetter("dateOfBirth")
    @JsonSerialize(using=DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getDateOfBirth ( ) { 
        return this.dateOfBirth;
    }
    
    /** SETTER
     * The date of birth for the person.
     */
    @JsonSetter("dateOfBirth")
    @JsonDeserialize(using=DateTimeHelper.SimpleDateDeserializer.class)
    public void setDateOfBirth (LocalDate value) { 
        this.dateOfBirth = value;
    }
 
}
