/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum BrandEnum {
    VISA, //TODO: Write general description for this element
    MASTERCARD, //TODO: Write general description for this element
    AMEX, //TODO: Write general description for this element
    DISCOVER; //TODO: Write general description for this element

    private static TreeMap<String, BrandEnum> valueMap = new TreeMap<String, BrandEnum>();
    private String value;

    static {
        VISA.value = "VISA";
        MASTERCARD.value = "MASTERCARD";
        AMEX.value = "AMEX";
        DISCOVER.value = "DISCOVER";

        valueMap.put("VISA", VISA);
        valueMap.put("MASTERCARD", MASTERCARD);
        valueMap.put("AMEX", AMEX);
        valueMap.put("DISCOVER", DISCOVER);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static BrandEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of BrandEnum values to list of string values
     * @param toConvert The list of BrandEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<BrandEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (BrandEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 