/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class BusinessUpdateIdentificationResourceBuilder {
    //the instance to build
    private BusinessUpdateIdentificationResource businessUpdateIdentificationResource;

    /**
     * Default constructor to initialize the instance
     */
    public BusinessUpdateIdentificationResourceBuilder() {
        businessUpdateIdentificationResource = new BusinessUpdateIdentificationResource();
    }

    /**
     * The type of identification [VAT, EIN, COMPANY_REGISTRATION_NUMBER, TAX_ID].
     */
    public BusinessUpdateIdentificationResourceBuilder type(BusinessIdTypeEnum type) {
        businessUpdateIdentificationResource.setType(type);
        return this;
    }

    /**
     * The display info for the identification.
     */
    public BusinessUpdateIdentificationResourceBuilder displayText(String displayText) {
        businessUpdateIdentificationResource.setDisplayText(displayText);
        return this;
    }

    /**
     * The key to vault that contains the data associated with the EIN, VAT or CRN id. This key will be generated when the identification is created at YapStone.
     */
    public BusinessUpdateIdentificationResourceBuilder businessIdDataToken(String businessIdDataToken) {
        businessUpdateIdentificationResource.setBusinessIdDataToken(businessIdDataToken);
        return this;
    }

    /**
     * The number associated with the identification.
     */
    public BusinessUpdateIdentificationResourceBuilder number(String number) {
        businessUpdateIdentificationResource.setNumber(number);
        return this;
    }

    /**
     * The level at witch the identification was issued (national, state, county, city, other)
     */
    public BusinessUpdateIdentificationResourceBuilder issuer(IssuerScopeEnum issuer) {
        businessUpdateIdentificationResource.setIssuer(issuer);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BusinessUpdateIdentificationResource build() {
        return businessUpdateIdentificationResource;
    }
}