/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum BusinessIdTypeEnum {
    VAT, //TODO: Write general description for this element
    EIN, //TODO: Write general description for this element
    COMPANY_REGISTRATION_NUMBER, //TODO: Write general description for this element
    TAX_ID; //TODO: Write general description for this element

    private static TreeMap<String, BusinessIdTypeEnum> valueMap = new TreeMap<String, BusinessIdTypeEnum>();
    private String value;

    static {
        VAT.value = "VAT";
        EIN.value = "EIN";
        COMPANY_REGISTRATION_NUMBER.value = "COMPANY_REGISTRATION_NUMBER";
        TAX_ID.value = "TAX_ID";

        valueMap.put("VAT", VAT);
        valueMap.put("EIN", EIN);
        valueMap.put("COMPANY_REGISTRATION_NUMBER", COMPANY_REGISTRATION_NUMBER);
        valueMap.put("TAX_ID", TAX_ID);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static BusinessIdTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of BusinessIdTypeEnum values to list of string values
     * @param toConvert The list of BusinessIdTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<BusinessIdTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (BusinessIdTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 