/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class BusinessApplicantAdminFieldsResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 96718198681821349L;
    private Boolean autoGraduated;
    /** GETTER
     * value for graduation policy
     */
    @JsonGetter("autoGraduated")
    public Boolean getAutoGraduated ( ) { 
        return this.autoGraduated;
    }
    
    /** SETTER
     * value for graduation policy
     */
    @JsonSetter("autoGraduated")
    public void setAutoGraduated (Boolean value) { 
        this.autoGraduated = value;
    }
 
}
