/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonTypeInfo(
          use = JsonTypeInfo.Id.NAME,
          include = JsonTypeInfo.As.EXISTING_PROPERTY,
          property = "type",
          defaultImpl = CapabilityResource.class,
          visible = true)
@JsonSubTypes({
    @Type(value = DirectDebtCapabilityResource.class, name = "directDebtCapabilityResource")
})
@JsonInclude(Include.ALWAYS)
public class CapabilityResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = -6590652636164234393L;
    private String type;
    private Object additionalProperties;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("additionalProperties")
    public Object getAdditionalProperties ( ) { 
        return this.additionalProperties;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("additionalProperties")
    public void setAdditionalProperties (Object value) { 
        this.additionalProperties = value;
    }
 
}
