/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class CardDataResourceBuilder {
    //the instance to build
    private CardDataResource cardDataResource;

    /**
     * Default constructor to initialize the instance
     */
    public CardDataResourceBuilder() {
        cardDataResource = new CardDataResource();
    }

    /**
     * Type of the card ( DEBIT, CREDIT, PREPAID)
     */
    public CardDataResourceBuilder cardType(CardTypeEnum cardType) {
        cardDataResource.setCardType(cardType);
        return this;
    }

    /**
     * Issuing authority
     */
    public CardDataResourceBuilder brand(BrandEnum brand) {
        cardDataResource.setBrand(brand);
        return this;
    }

    public CardDataResourceBuilder cardTokenSource(CardTokenSourceEnum cardTokenSource) {
        cardDataResource.setCardTokenSource(cardTokenSource);
        return this;
    }

    /**
     * Card Expiration Date.
     */
    public CardDataResourceBuilder expirationDate(ExpirationDateResource expirationDate) {
        cardDataResource.setExpirationDate(expirationDate);
        return this;
    }

    /**
     * The address of the application, asset, bank, etc.
     */
    public CardDataResourceBuilder billingAddress(AddressResource billingAddress) {
        cardDataResource.setBillingAddress(billingAddress);
        return this;
    }

    /**
     * Name on the card
     */
    public CardDataResourceBuilder cardHolderName(String cardHolderName) {
        cardDataResource.setCardHolderName(cardHolderName);
        return this;
    }

    /**
     * The token to get the card details from vault.
     */
    public CardDataResourceBuilder cardTokenData(String cardTokenData) {
        cardDataResource.setCardTokenData(cardTokenData);
        return this;
    }

    /**
     * The card number.
     */
    public CardDataResourceBuilder cardNumber(String cardNumber) {
        cardDataResource.setCardNumber(cardNumber);
        return this;
    }

    /**
     * CVV number.
     */
    public CardDataResourceBuilder cvv(String cvv) {
        cardDataResource.setCvv(cvv);
        return this;
    }

    /**
     * Need to be 3 digit currency code(ISO 3). USD, CAD, EUR, GBP, DOP, BSD, CRC, ANG, JMD, MXN, CHF.
     */
    public CardDataResourceBuilder currency(String currency) {
        cardDataResource.setCurrency(currency);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CardDataResource build() {
        return cardDataResource;
    }
}