/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum CardTypeEnum {
    DEBIT, //TODO: Write general description for this element
    CREDIT, //TODO: Write general description for this element
    PREPAID; //TODO: Write general description for this element

    private static TreeMap<String, CardTypeEnum> valueMap = new TreeMap<String, CardTypeEnum>();
    private String value;

    static {
        DEBIT.value = "DEBIT";
        CREDIT.value = "CREDIT";
        PREPAID.value = "PREPAID";

        valueMap.put("DEBIT", DEBIT);
        valueMap.put("CREDIT", CREDIT);
        valueMap.put("PREPAID", PREPAID);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static CardTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CardTypeEnum values to list of string values
     * @param toConvert The list of CardTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<CardTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (CardTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 