/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.DateTime;

public class ConsentBuilder {
    //the instance to build
    private Consent consent;

    /**
     * Default constructor to initialize the instance
     */
    public ConsentBuilder() {
        consent = new Consent();
    }

    public ConsentBuilder type(String type) {
        consent.setType(type);
        return this;
    }

    /**
     * Indicates the acceptance of the T&Cs.
     */
    public ConsentBuilder accepted(boolean accepted) {
        consent.setAccepted(accepted);
        return this;
    }

    /**
     * Time of the consent
     */
    public ConsentBuilder timeOfConsent(DateTime timeOfConsent) {
        consent.setTimeOfConsent(timeOfConsent);
        return this;
    }

    /**
     * Version of the consent
     */
    public ConsentBuilder version(int version) {
        consent.setVersion(version);
        return this;
    }

    /**
     * IP Address of machine from which consent was given
     */
    public ConsentBuilder ipAddress(String ipAddress) {
        consent.setIpAddress(ipAddress);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Consent build() {
        return consent;
    }
}