/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class ContractUpdateRequestBuilder {
    //the instance to build
    private ContractUpdateRequest contractUpdateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ContractUpdateRequestBuilder() {
        contractUpdateRequest = new ContractUpdateRequest();
    }

    /**
     * The partners externalId id for entity.
     */
    public ContractUpdateRequestBuilder externalId(String externalId) {
        contractUpdateRequest.setExternalId(externalId);
        return this;
    }

    /**
     * The unique id of the Applicant Resource.
     */
    public ContractUpdateRequestBuilder applicantId(String applicantId) {
        contractUpdateRequest.setApplicantId(applicantId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContractUpdateRequest build() {
        return contractUpdateRequest;
    }
}