/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum CreditorIdEnum {
    MARKETPLACE, //TODO: Write general description for this element
    YAPSTONE; //TODO: Write general description for this element

    private static TreeMap<String, CreditorIdEnum> valueMap = new TreeMap<String, CreditorIdEnum>();
    private String value;

    static {
        MARKETPLACE.value = "MARKETPLACE";
        YAPSTONE.value = "YAPSTONE";

        valueMap.put("MARKETPLACE", MARKETPLACE);
        valueMap.put("YAPSTONE", YAPSTONE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static CreditorIdEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CreditorIdEnum values to list of string values
     * @param toConvert The list of CreditorIdEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<CreditorIdEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (CreditorIdEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 