/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.DateTime;

public class CustomerConsentResourceBuilder {
    //the instance to build
    private CustomerConsentResource customerConsentResource;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerConsentResourceBuilder() {
        customerConsentResource = new CustomerConsentResource();
    }

    /**
     * The timestamp in ISO 8601 format when the user consented.
     */
    public CustomerConsentResourceBuilder timeOfConsent(DateTime timeOfConsent) {
        customerConsentResource.setTimeOfConsent(timeOfConsent);
        return this;
    }

    public CustomerConsentResourceBuilder type(CustomerConsentTypeEnum type) {
        customerConsentResource.setType(type);
        return this;
    }

    /**
     * The version of the consent if there is one.
     */
    public CustomerConsentResourceBuilder version(Integer version) {
        customerConsentResource.setVersion(version);
        return this;
    }

    /**
     * Indicates the acceptance of the T&Cs.
     */
    public CustomerConsentResourceBuilder accepted(Boolean accepted) {
        customerConsentResource.setAccepted(accepted);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerConsentResource build() {
        return customerConsentResource;
    }
}