/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.LocalDate;

public class CustomerAdminResourceBuilder {
    //the instance to build
    private CustomerAdminResource customerAdminResource;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerAdminResourceBuilder() {
        customerAdminResource = new CustomerAdminResource();
    }

    /**
     * The resource identifier for the customer.
     */
    public CustomerAdminResourceBuilder id(String id) {
        customerAdminResource.setId(id);
        return this;
    }

    /**
     * The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix.
     */
    public CustomerAdminResourceBuilder name(CustomerNameResource name) {
        customerAdminResource.setName(name);
        return this;
    }

    /**
     * The phone number.
     */
    public CustomerAdminResourceBuilder phone(CustomerPhoneResource phone) {
        customerAdminResource.setPhone(phone);
        return this;
    }

    /**
     * The email address.
     */
    public CustomerAdminResourceBuilder email(String email) {
        customerAdminResource.setEmail(email);
        return this;
    }

    /**
     * The address of the customer.
     */
    public CustomerAdminResourceBuilder address(CustomerAddressResource address) {
        customerAdminResource.setAddress(address);
        return this;
    }

    /**
     * The goverment identification information.
     */
    public CustomerAdminResourceBuilder govIdentification(CustomerGovernmentIdentificationResource govIdentification) {
        customerAdminResource.setGovIdentification(govIdentification);
        return this;
    }

    public CustomerAdminResourceBuilder dateOfBirth(LocalDate dateOfBirth) {
        customerAdminResource.setDateOfBirth(dateOfBirth);
        return this;
    }

    public CustomerAdminResourceBuilder metadata(Object metadata) {
        customerAdminResource.setMetadata(metadata);
        return this;
    }

    public CustomerAdminResourceBuilder consents(List<CustomerConsentResource> consents) {
        customerAdminResource.setConsents(consents);
        return this;
    }

    /**
     * The Mktplaces unique identifier for the Customer.
     */
    public CustomerAdminResourceBuilder externalId(String externalId) {
        customerAdminResource.setExternalId(externalId);
        return this;
    }

    /**
     * The status of the entity.
     */
    public CustomerAdminResourceBuilder status(CustomerEntityProductcustomerStatusResource status) {
        customerAdminResource.setStatus(status);
        return this;
    }

    /**
     * The name of the business.
     */
    public CustomerAdminResourceBuilder businessName(String businessName) {
        customerAdminResource.setBusinessName(businessName);
        return this;
    }

    /**
     * The type of business unit (sole_prop, corp, llc)
     */
    public CustomerAdminResourceBuilder businessType(BusinessTypeEnum businessType) {
        customerAdminResource.setBusinessType(businessType);
        return this;
    }

    /**
     * The party id for the customer.
     */
    public CustomerAdminResourceBuilder partyId(String partyId) {
        customerAdminResource.setPartyId(partyId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerAdminResource build() {
        return customerAdminResource;
    }
}