/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class CustomerHistoryResourceBuilder {
    //the instance to build
    private CustomerHistoryResource customerHistoryResource;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerHistoryResourceBuilder() {
        customerHistoryResource = new CustomerHistoryResource();
    }

    /**
     * The information about the customer as an asset owner.
     */
    public CustomerHistoryResourceBuilder propertyOwner(PropertyOwnerResource propertyOwner) {
        customerHistoryResource.setPropertyOwner(propertyOwner);
        return this;
    }

    /**
     * The customer history as a traveler.
     */
    public CustomerHistoryResourceBuilder traveler(TravelerResource traveler) {
        customerHistoryResource.setTraveler(traveler);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerHistoryResource build() {
        return customerHistoryResource;
    }
}