/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.LocalDate;

public class CustomerResourceBuilder {
    //the instance to build
    private CustomerResource customerResource;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerResourceBuilder() {
        customerResource = new CustomerResource();
    }

    /**
     * The resource identifier for the customer.
     */
    public CustomerResourceBuilder id(String id) {
        customerResource.setId(id);
        return this;
    }

    /**
     * The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix.
     */
    public CustomerResourceBuilder name(CustomerNameResource name) {
        customerResource.setName(name);
        return this;
    }

    /**
     * The phone number.
     */
    public CustomerResourceBuilder phone(CustomerPhoneResource phone) {
        customerResource.setPhone(phone);
        return this;
    }

    /**
     * The email address.
     */
    public CustomerResourceBuilder email(String email) {
        customerResource.setEmail(email);
        return this;
    }

    /**
     * The address of the customer.
     */
    public CustomerResourceBuilder address(CustomerAddressResource address) {
        customerResource.setAddress(address);
        return this;
    }

    /**
     * The goverment identification information.
     */
    public CustomerResourceBuilder govIdentification(CustomerGovernmentIdentificationResource govIdentification) {
        customerResource.setGovIdentification(govIdentification);
        return this;
    }

    public CustomerResourceBuilder dateOfBirth(LocalDate dateOfBirth) {
        customerResource.setDateOfBirth(dateOfBirth);
        return this;
    }

    public CustomerResourceBuilder metadata(Object metadata) {
        customerResource.setMetadata(metadata);
        return this;
    }

    public CustomerResourceBuilder consents(List<CustomerConsentResource> consents) {
        customerResource.setConsents(consents);
        return this;
    }

    /**
     * The Mktplaces unique identifier for the Customer.
     */
    public CustomerResourceBuilder externalId(String externalId) {
        customerResource.setExternalId(externalId);
        return this;
    }

    /**
     * The status of the entity.
     */
    public CustomerResourceBuilder status(CustomerEntityProductcustomerStatusResource status) {
        customerResource.setStatus(status);
        return this;
    }

    /**
     * The name of the business.
     */
    public CustomerResourceBuilder businessName(String businessName) {
        customerResource.setBusinessName(businessName);
        return this;
    }

    /**
     * The type of business unit (sole_prop, corp, llc)
     */
    public CustomerResourceBuilder businessType(BusinessTypeEnum businessType) {
        customerResource.setBusinessType(businessType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerResource build() {
        return customerResource;
    }
}