/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum CustomerGovernmentIdTypeEnum {
    LAST_FOUR_SSN; //TODO: Write general description for this element

    private static TreeMap<String, CustomerGovernmentIdTypeEnum> valueMap = new TreeMap<String, CustomerGovernmentIdTypeEnum>();
    private String value;

    static {
        LAST_FOUR_SSN.value = "LAST_FOUR_SSN";

        valueMap.put("LAST_FOUR_SSN", LAST_FOUR_SSN);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static CustomerGovernmentIdTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CustomerGovernmentIdTypeEnum values to list of string values
     * @param toConvert The list of CustomerGovernmentIdTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<CustomerGovernmentIdTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (CustomerGovernmentIdTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 