/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CustomerNameResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8471178996109717846L;
    private HonorificPrefixEnum honorificPrefix;
    private String first;
    private String middle;
    private String last;
    private String additionalLast;
    private String honorificSuffix;
    /** GETTER
     * The persons title.
     */
    @JsonGetter("honorificPrefix")
    public HonorificPrefixEnum getHonorificPrefix ( ) { 
        return this.honorificPrefix;
    }
    
    /** SETTER
     * The persons title.
     */
    @JsonSetter("honorificPrefix")
    public void setHonorificPrefix (HonorificPrefixEnum value) { 
        this.honorificPrefix = value;
    }
 
    /** GETTER
     * The persons first name.
     */
    @JsonGetter("first")
    public String getFirst ( ) { 
        return this.first;
    }
    
    /** SETTER
     * The persons first name.
     */
    @JsonSetter("first")
    public void setFirst (String value) { 
        this.first = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("middle")
    public String getMiddle ( ) { 
        return this.middle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("middle")
    public void setMiddle (String value) { 
        this.middle = value;
    }
 
    /** GETTER
     * The persons last name.
     */
    @JsonGetter("last")
    public String getLast ( ) { 
        return this.last;
    }
    
    /** SETTER
     * The persons last name.
     */
    @JsonSetter("last")
    public void setLast (String value) { 
        this.last = value;
    }
 
    /** GETTER
     * The 2nd last name of the person.
     */
    @JsonGetter("additionalLast")
    public String getAdditionalLast ( ) { 
        return this.additionalLast;
    }
    
    /** SETTER
     * The 2nd last name of the person.
     */
    @JsonSetter("additionalLast")
    public void setAdditionalLast (String value) { 
        this.additionalLast = value;
    }
 
    /** GETTER
     * The persons title.
     */
    @JsonGetter("honorificSuffix")
    public String getHonorificSuffix ( ) { 
        return this.honorificSuffix;
    }
    
    /** SETTER
     * The persons title.
     */
    @JsonSetter("honorificSuffix")
    public void setHonorificSuffix (String value) { 
        this.honorificSuffix = value;
    }
 
}
