/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class CustomerAddressResourceBuilder {
    //the instance to build
    private CustomerAddressResource customerAddressResource;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerAddressResourceBuilder() {
        customerAddressResource = new CustomerAddressResource();
    }

    /**
     * The street address line 1.
     */
    public CustomerAddressResourceBuilder street1(String street1) {
        customerAddressResource.setStreet1(street1);
        return this;
    }

    /**
     * The street address line 2.
     */
    public CustomerAddressResourceBuilder street2(String street2) {
        customerAddressResource.setStreet2(street2);
        return this;
    }

    /**
     * The street address line 3.
     */
    public CustomerAddressResourceBuilder street3(String street3) {
        customerAddressResource.setStreet3(street3);
        return this;
    }

    /**
     * The street address line 4.
     */
    public CustomerAddressResourceBuilder street4(String street4) {
        customerAddressResource.setStreet4(street4);
        return this;
    }

    /**
     * The name of the city.
     */
    public CustomerAddressResourceBuilder city(String city) {
        customerAddressResource.setCity(city);
        return this;
    }

    /**
     * The state or province where the address resides.
     */
    public CustomerAddressResourceBuilder state(String state) {
        customerAddressResource.setState(state);
        return this;
    }

    /**
     * The postal code of the address.
     */
    public CustomerAddressResourceBuilder postalCode(String postalCode) {
        customerAddressResource.setPostalCode(postalCode);
        return this;
    }

    /**
     * The 3-letter countryCode of the address.
     */
    public CustomerAddressResourceBuilder countryCode(String countryCode) {
        customerAddressResource.setCountryCode(countryCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerAddressResource build() {
        return customerAddressResource;
    }
}