/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class CustomerDeactivateResponseBuilder {
    //the instance to build
    private CustomerDeactivateResponse customerDeactivateResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerDeactivateResponseBuilder() {
        customerDeactivateResponse = new CustomerDeactivateResponse();
    }

    public CustomerDeactivateResponseBuilder message(String message) {
        customerDeactivateResponse.setMessage(message);
        return this;
    }

    /**
     * List of contracts successfully de-activated due to cascade, otherwise empty
     */
    public CustomerDeactivateResponseBuilder cascadedContracts(List<String> cascadedContracts) {
        customerDeactivateResponse.setCascadedContracts(cascadedContracts);
        return this;
    }

    /**
     * List of contracts failed to de-activate while cascade, otherwise empty
     */
    public CustomerDeactivateResponseBuilder failedContracts(List<String> failedContracts) {
        customerDeactivateResponse.setFailedContracts(failedContracts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerDeactivateResponse build() {
        return customerDeactivateResponse;
    }
}