/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class DeactivateResponseBuilder {
    //the instance to build
    private DeactivateResponse deactivateResponse;

    /**
     * Default constructor to initialize the instance
     */
    public DeactivateResponseBuilder() {
        deactivateResponse = new DeactivateResponse();
    }

    public DeactivateResponseBuilder message(String message) {
        deactivateResponse.setMessage(message);
        return this;
    }

    /**
     * List of contracts successfully de-activated due to cascade, otherwise empty
     */
    public DeactivateResponseBuilder cascadedContracts(List<String> cascadedContracts) {
        deactivateResponse.setCascadedContracts(cascadedContracts);
        return this;
    }

    /**
     * List of contracts failed to de-activate while cascade, otherwise empty
     */
    public DeactivateResponseBuilder failedContracts(List<String> failedContracts) {
        deactivateResponse.setFailedContracts(failedContracts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeactivateResponse build() {
        return deactivateResponse;
    }
}