/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class DirectDebitConsentResourceBuilder 
        extends ConsentBuilder {
    //the instance to build
    private DirectDebitConsentResource directDebitConsentResource;

    /**
     * Default constructor to initialize the instance
     */
    public DirectDebitConsentResourceBuilder() {
        directDebitConsentResource = new DirectDebitConsentResource();
    }

    public DirectDebitConsentResourceBuilder type(Object type) {
        directDebitConsentResource.setType(type);
        return this;
    }

    /**
     * The reference number that client has for the mandate
     */
    public DirectDebitConsentResourceBuilder externalId(String externalId) {
        directDebitConsentResource.setExternalId(externalId);
        return this;
    }

    /**
     * The creditor Id
     */
    public DirectDebitConsentResourceBuilder creditorId(CreditorIdEnum creditorId) {
        directDebitConsentResource.setCreditorId(creditorId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DirectDebitConsentResource build() {
        return directDebitConsentResource;
    }
}