/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class EntityHistoryResourceBuilder {
    //the instance to build
    private EntityHistoryResource entityHistoryResource;

    /**
     * Default constructor to initialize the instance
     */
    public EntityHistoryResourceBuilder() {
        entityHistoryResource = new EntityHistoryResource();
    }

    /**
     * A list of entity update events.
     */
    public EntityHistoryResourceBuilder results(List<EntityUpdateEvent> results) {
        entityHistoryResource.setResults(results);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EntityHistoryResource build() {
        return entityHistoryResource;
    }
}