/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.DateTime;

public class EntityUpdateEventBuilder {
    //the instance to build
    private EntityUpdateEvent entityUpdateEvent;

    /**
     * Default constructor to initialize the instance
     */
    public EntityUpdateEventBuilder() {
        entityUpdateEvent = new EntityUpdateEvent();
    }

    /**
     * Unique Id of entity.
     */
    public EntityUpdateEventBuilder entityId(String entityId) {
        entityUpdateEvent.setEntityId(entityId);
        return this;
    }

    /**
     * List of updated attributes.
     */
    public EntityUpdateEventBuilder updatedAttributes(List<EntityUpdatedAttribute> updatedAttributes) {
        entityUpdateEvent.setUpdatedAttributes(updatedAttributes);
        return this;
    }

    /**
     * Name of user.
     */
    public EntityUpdateEventBuilder userName(String userName) {
        entityUpdateEvent.setUserName(userName);
        return this;
    }

    /**
     * The timestamp in ISO 8601 format when the entity last updated.
     */
    public EntityUpdateEventBuilder lastUpdated(DateTime lastUpdated) {
        entityUpdateEvent.setLastUpdated(lastUpdated);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EntityUpdateEvent build() {
        return entityUpdateEvent;
    }
}