/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yapstone.apiuat.DateTimeHelper;
import org.joda.time.DateTime;

@JsonInclude(Include.ALWAYS)
public class EntityUpdateEvent 
        implements java.io.Serializable {
    private static final long serialVersionUID = 139768635446582860L;
    private String entityId;
    private List<EntityUpdatedAttribute> updatedAttributes;
    private String userName;
    private DateTime lastUpdated;
    /** GETTER
     * Unique Id of entity.
     */
    @JsonGetter("entityId")
    public String getEntityId ( ) { 
        return this.entityId;
    }
    
    /** SETTER
     * Unique Id of entity.
     */
    @JsonSetter("entityId")
    public void setEntityId (String value) { 
        this.entityId = value;
    }
 
    /** GETTER
     * List of updated attributes.
     */
    @JsonGetter("updatedAttributes")
    public List<EntityUpdatedAttribute> getUpdatedAttributes ( ) { 
        return this.updatedAttributes;
    }
    
    /** SETTER
     * List of updated attributes.
     */
    @JsonSetter("updatedAttributes")
    public void setUpdatedAttributes (List<EntityUpdatedAttribute> value) { 
        this.updatedAttributes = value;
    }
 
    /** GETTER
     * Name of user.
     */
    @JsonGetter("userName")
    public String getUserName ( ) { 
        return this.userName;
    }
    
    /** SETTER
     * Name of user.
     */
    @JsonSetter("userName")
    public void setUserName (String value) { 
        this.userName = value;
    }
 
    /** GETTER
     * The timestamp in ISO 8601 format when the entity last updated.
     */
    @JsonGetter("lastUpdated")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getLastUpdated ( ) { 
        return this.lastUpdated;
    }
    
    /** SETTER
     * The timestamp in ISO 8601 format when the entity last updated.
     */
    @JsonSetter("lastUpdated")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setLastUpdated (DateTime value) { 
        this.lastUpdated = value;
    }
 
}
