/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum EntityTypeEnum {
    MARKETPLACE, //TODO: Write general description for this element
    MERCHANT, //TODO: Write general description for this element
    ASSET_LISTING, //TODO: Write general description for this element
    CUSTOMER; //TODO: Write general description for this element

    private static TreeMap<String, EntityTypeEnum> valueMap = new TreeMap<String, EntityTypeEnum>();
    private String value;

    static {
        MARKETPLACE.value = "MARKETPLACE";
        MERCHANT.value = "MERCHANT";
        ASSET_LISTING.value = "ASSET_LISTING";
        CUSTOMER.value = "CUSTOMER";

        valueMap.put("MARKETPLACE", MARKETPLACE);
        valueMap.put("MERCHANT", MERCHANT);
        valueMap.put("ASSET_LISTING", ASSET_LISTING);
        valueMap.put("CUSTOMER", CUSTOMER);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static EntityTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of EntityTypeEnum values to list of string values
     * @param toConvert The list of EntityTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<EntityTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (EntityTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 