/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class EntityUpdatedAttribute 
        implements java.io.Serializable {
    private static final long serialVersionUID = 48773628142365450L;
    private String name;
    private Object newValue;
    private Object oldValue;
    /** GETTER
     * Name of attribute.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Name of attribute.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * New value of attribute.
     */
    @JsonGetter("newValue")
    public Object getNewValue ( ) { 
        return this.newValue;
    }
    
    /** SETTER
     * New value of attribute.
     */
    @JsonSetter("newValue")
    public void setNewValue (Object value) { 
        this.newValue = value;
    }
 
    /** GETTER
     * Old value of attribute.
     */
    @JsonGetter("oldValue")
    public Object getOldValue ( ) { 
        return this.oldValue;
    }
    
    /** SETTER
     * Old value of attribute.
     */
    @JsonSetter("oldValue")
    public void setOldValue (Object value) { 
        this.oldValue = value;
    }
 
}
