/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonTypeInfo(
          use = JsonTypeInfo.Id.NAME,
          include = JsonTypeInfo.As.EXISTING_PROPERTY,
          property = "type",
          defaultImpl = IndividualApplicantResource.class,
          visible = true)
@JsonSubTypes({
    @Type(value = IndividualApplicantAdminResource.class, name = "individualApplicantAdminResource")
})
@JsonInclude(Include.ALWAYS)
public class IndividualApplicantResource 
        extends ApplicantResource {
    private static final long serialVersionUID = -6926974891465716945L;
    private ProfileResource individualProfile;
    /** GETTER
     * User profile information. Contains data about the person such as name, address, phone, email, etc.
     */
    @JsonGetter("individualProfile")
    public ProfileResource getIndividualProfile ( ) { 
        return this.individualProfile;
    }
    
    /** SETTER
     * User profile information. Contains data about the person such as name, address, phone, email, etc.
     */
    @JsonSetter("individualProfile")
    public void setIndividualProfile (ProfileResource value) { 
        this.individualProfile = value;
    }
 
}
