/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class InstrumentOperationalStatusBuilder {
    //the instance to build
    private InstrumentOperationalStatus instrumentOperationalStatus;

    /**
     * Default constructor to initialize the instance
     */
    public InstrumentOperationalStatusBuilder() {
        instrumentOperationalStatus = new InstrumentOperationalStatus();
    }

    /**
     * The status of the entity.
     */
    public InstrumentOperationalStatusBuilder payoutStatus(ActionStatusResource payoutStatus) {
        instrumentOperationalStatus.setPayoutStatus(payoutStatus);
        return this;
    }

    /**
     * The status of the entity.
     */
    public InstrumentOperationalStatusBuilder debitStatus(ActionStatusResource debitStatus) {
        instrumentOperationalStatus.setDebitStatus(debitStatus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InstrumentOperationalStatus build() {
        return instrumentOperationalStatus;
    }
}