/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum IssuerScopeEnum {
    CITY, //TODO: Write general description for this element
    COUNTY, //TODO: Write general description for this element
    NATIONAL, //TODO: Write general description for this element
    STATE, //TODO: Write general description for this element
    OTHER; //TODO: Write general description for this element

    private static TreeMap<String, IssuerScopeEnum> valueMap = new TreeMap<String, IssuerScopeEnum>();
    private String value;

    static {
        CITY.value = "CITY";
        COUNTY.value = "COUNTY";
        NATIONAL.value = "NATIONAL";
        STATE.value = "STATE";
        OTHER.value = "OTHER";

        valueMap.put("CITY", CITY);
        valueMap.put("COUNTY", COUNTY);
        valueMap.put("NATIONAL", NATIONAL);
        valueMap.put("STATE", STATE);
        valueMap.put("OTHER", OTHER);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static IssuerScopeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of IssuerScopeEnum values to list of string values
     * @param toConvert The list of IssuerScopeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<IssuerScopeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (IssuerScopeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 