/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class MarketplaceResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7959213549136039426L;
    private String id;
    private String name;
    private CustomerPhoneResource phone;
    private String email;
    private CustomerAddressResource address;
    /** GETTER
     * The marketplace Id.
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * The marketplace Id.
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * The marketplace name.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The marketplace name.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The phone number.
     */
    @JsonGetter("phone")
    public CustomerPhoneResource getPhone ( ) { 
        return this.phone;
    }
    
    /** SETTER
     * The phone number.
     */
    @JsonSetter("phone")
    public void setPhone (CustomerPhoneResource value) { 
        this.phone = value;
    }
 
    /** GETTER
     * The Marketplace email address.
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * The Marketplace email address.
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
    /** GETTER
     * The address of the customer.
     */
    @JsonGetter("address")
    public CustomerAddressResource getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * The address of the customer.
     */
    @JsonSetter("address")
    public void setAddress (CustomerAddressResource value) { 
        this.address = value;
    }
 
}
