/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class MarketPlacePropertyResourceBuilder {
    //the instance to build
    private MarketPlacePropertyResource marketPlacePropertyResource;

    /**
     * Default constructor to initialize the instance
     */
    public MarketPlacePropertyResourceBuilder() {
        marketPlacePropertyResource = new MarketPlacePropertyResource();
    }

    /**
     * The marketplace score property.
     */
    public MarketPlacePropertyResourceBuilder score(Double score) {
        marketPlacePropertyResource.setScore(score);
        return this;
    }

    /**
     * The properties reservation settings.
     */
    public MarketPlacePropertyResourceBuilder reservationSetting(ReservationSettingResource reservationSetting) {
        marketPlacePropertyResource.setReservationSetting(reservationSetting);
        return this;
    }

    /**
     * The checkin time.
     */
    public MarketPlacePropertyResourceBuilder checkIn(String checkIn) {
        marketPlacePropertyResource.setCheckIn(checkIn);
        return this;
    }

    /**
     * The checkout time.
     */
    public MarketPlacePropertyResourceBuilder checkOut(String checkOut) {
        marketPlacePropertyResource.setCheckOut(checkOut);
        return this;
    }

    /**
     * The cancellation policy for the property.
     */
    public MarketPlacePropertyResourceBuilder cancellationPolicy(String cancellationPolicy) {
        marketPlacePropertyResource.setCancellationPolicy(cancellationPolicy);
        return this;
    }

    /**
     * Property stats and counts.
     */
    public MarketPlacePropertyResourceBuilder propertyTracker(PropertyTrackerResource propertyTracker) {
        marketPlacePropertyResource.setPropertyTracker(propertyTracker);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MarketPlacePropertyResource build() {
        return marketPlacePropertyResource;
    }
}