/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class MarketplaceProductPayoutInstrumentUpdateBuilder {
    //the instance to build
    private MarketplaceProductPayoutInstrumentUpdate marketplaceProductPayoutInstrumentUpdate;

    /**
     * Default constructor to initialize the instance
     */
    public MarketplaceProductPayoutInstrumentUpdateBuilder() {
        marketplaceProductPayoutInstrumentUpdate = new MarketplaceProductPayoutInstrumentUpdate();
    }

    /**
     * payout instrument id
     */
    public MarketplaceProductPayoutInstrumentUpdateBuilder id(String id) {
        marketplaceProductPayoutInstrumentUpdate.setId(id);
        return this;
    }

    /**
     * The status of the entity.
     */
    public MarketplaceProductPayoutInstrumentUpdateBuilder payoutStatus(ActionStatusResource payoutStatus) {
        marketplaceProductPayoutInstrumentUpdate.setPayoutStatus(payoutStatus);
        return this;
    }

    /**
     * The operation to be performed
     */
    public MarketplaceProductPayoutInstrumentUpdateBuilder op(PatchOperationEnum op) {
        marketplaceProductPayoutInstrumentUpdate.setOp(op);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MarketplaceProductPayoutInstrumentUpdate build() {
        return marketplaceProductPayoutInstrumentUpdate;
    }
}