/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class MarketPlaceApplicantResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = -120310286071502809L;
    private CustomerHistoryResource customerHistory;
    /** GETTER
     * The marketplace's customer information.
     */
    @JsonGetter("customerHistory")
    public CustomerHistoryResource getCustomerHistory ( ) { 
        return this.customerHistory;
    }
    
    /** SETTER
     * The marketplace's customer information.
     */
    @JsonSetter("customerHistory")
    public void setCustomerHistory (CustomerHistoryResource value) { 
        this.customerHistory = value;
    }
 
}
