/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class MetaPage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 12888408838362858L;
    private Page page;
    /** GETTER
     * Pagination support
     */
    @JsonGetter("page")
    public Page getPage ( ) { 
        return this.page;
    }
    
    /** SETTER
     * Pagination support
     */
    @JsonSetter("page")
    public void setPage (Page value) { 
        this.page = value;
    }
 
}
