/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class MoneyResourceBuilder {
    //the instance to build
    private MoneyResource moneyResource;

    /**
     * Default constructor to initialize the instance
     */
    public MoneyResourceBuilder() {
        moneyResource = new MoneyResource();
    }

    /**
     * The ISO currency code for the moneyResource.
     */
    public MoneyResourceBuilder currencyCode(String currencyCode) {
        moneyResource.setCurrencyCode(currencyCode);
        return this;
    }

    /**
     * The amount of the in cents.
     */
    public MoneyResourceBuilder value(long value) {
        moneyResource.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MoneyResource build() {
        return moneyResource;
    }
}