/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class OfferingResponseBuilder 
        extends RestResponseBuilder {
    //the instance to build
    private OfferingResponse offeringResponse;

    /**
     * Default constructor to initialize the instance
     */
    public OfferingResponseBuilder() {
        offeringResponse = new OfferingResponse();
    }

    public OfferingResponseBuilder items(List<OfferingResource> items) {
        offeringResponse.setItems(items);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OfferingResponse build() {
        return offeringResponse;
    }
}