/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class PaginationBuilder {
    //the instance to build
    private Pagination pagination;

    /**
     * Default constructor to initialize the instance
     */
    public PaginationBuilder() {
        pagination = new Pagination();
    }

    public PaginationBuilder totalCount(Long totalCount) {
        pagination.setTotalCount(totalCount);
        return this;
    }

    public PaginationBuilder page(int page) {
        pagination.setPage(page);
        return this;
    }

    public PaginationBuilder size(int size) {
        pagination.setSize(size);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Pagination build() {
        return pagination;
    }
}