/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class PayoutProductResourceBuilder {
    //the instance to build
    private PayoutProductResource payoutProductResource;

    /**
     * Default constructor to initialize the instance
     */
    public PayoutProductResourceBuilder() {
        payoutProductResource = new PayoutProductResource();
    }

    /**
     * The unique id of the resource
     */
    public PayoutProductResourceBuilder id(String id) {
        payoutProductResource.setId(id);
        return this;
    }

    /**
     * An array of consents.
     */
    public PayoutProductResourceBuilder consents(List<ConsentResource> consents) {
        payoutProductResource.setConsents(consents);
        return this;
    }

    /**
     * The status and reason for the status of the entity.
     */
    public PayoutProductResourceBuilder status(StatusReasonResource status) {
        payoutProductResource.setStatus(status);
        return this;
    }

    /**
     * payout instrumnet id
     */
    public PayoutProductResourceBuilder payoutInstrumentId(String payoutInstrumentId) {
        payoutProductResource.setPayoutInstrumentId(payoutInstrumentId);
        return this;
    }

    /**
     * The status of the entity.
     */
    public PayoutProductResourceBuilder creditStatus(ActionStatusResource creditStatus) {
        payoutProductResource.setCreditStatus(creditStatus);
        return this;
    }

    /**
     * The status of the entity.
     */
    public PayoutProductResourceBuilder debitStatus(ActionStatusResource debitStatus) {
        payoutProductResource.setDebitStatus(debitStatus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PayoutProductResource build() {
        return payoutProductResource;
    }
}