/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PayoutInstrumentUpdateRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 9128011347765466907L;
    private String externalId;
    private BankAccountResource bankAccount;
    private CardDataResource paymentCard;
    private Type2Enum type;
    private List<String> managedBy;
    private EntityProductStatusResource status;
    private InstrumentOperationalStatus operationalStatus;
    private OwnerRequest owner;
    private List<Consent> consents;
    private List<ProductEnum> products;
    /** GETTER
     * The partners externalId id for the Payout Instrument.
     */
    @JsonGetter("externalId")
    public String getExternalId ( ) { 
        return this.externalId;
    }
    
    /** SETTER
     * The partners externalId id for the Payout Instrument.
     */
    @JsonSetter("externalId")
    public void setExternalId (String value) { 
        this.externalId = value;
    }
 
    /** GETTER
     * The Bank account information.
     */
    @JsonGetter("bankAccount")
    public BankAccountResource getBankAccount ( ) { 
        return this.bankAccount;
    }
    
    /** SETTER
     * The Bank account information.
     */
    @JsonSetter("bankAccount")
    public void setBankAccount (BankAccountResource value) { 
        this.bankAccount = value;
    }
 
    /** GETTER
     * Payment card details.
     */
    @JsonGetter("paymentCard")
    public CardDataResource getPaymentCard ( ) { 
        return this.paymentCard;
    }
    
    /** SETTER
     * Payment card details.
     */
    @JsonSetter("paymentCard")
    public void setPaymentCard (CardDataResource value) { 
        this.paymentCard = value;
    }
 
    /** GETTER
     * The type of finanancial instrument [BANK_ACCOUNT]
     */
    @JsonGetter("type")
    public Type2Enum getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The type of finanancial instrument [BANK_ACCOUNT]
     */
    @JsonSetter("type")
    public void setType (Type2Enum value) { 
        this.type = value;
    }
 
    /** GETTER
     * The entity manages the Instrument. It can be merchant or marketplace.
     */
    @JsonGetter("managedBy")
    public List<String> getManagedBy ( ) { 
        return this.managedBy;
    }
    
    /** SETTER
     * The entity manages the Instrument. It can be merchant or marketplace.
     */
    @JsonSetter("managedBy")
    public void setManagedBy (List<String> value) { 
        this.managedBy = value;
    }
 
    /** GETTER
     * The status of the entity.
     */
    @JsonGetter("status")
    public EntityProductStatusResource getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The status of the entity.
     */
    @JsonSetter("status")
    public void setStatus (EntityProductStatusResource value) { 
        this.status = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("operationalStatus")
    public InstrumentOperationalStatus getOperationalStatus ( ) { 
        return this.operationalStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("operationalStatus")
    public void setOperationalStatus (InstrumentOperationalStatus value) { 
        this.operationalStatus = value;
    }
 
    /** GETTER
     * The owner of the asset
     */
    @JsonGetter("owner")
    public OwnerRequest getOwner ( ) { 
        return this.owner;
    }
    
    /** SETTER
     * The owner of the asset
     */
    @JsonSetter("owner")
    public void setOwner (OwnerRequest value) { 
        this.owner = value;
    }
 
    /** GETTER
     * list of consent requests
     */
    @JsonGetter("consents")
    public List<Consent> getConsents ( ) { 
        return this.consents;
    }
    
    /** SETTER
     * list of consent requests
     */
    @JsonSetter("consents")
    public void setConsents (List<Consent> value) { 
        this.consents = value;
    }
 
    /** GETTER
     * Products requested by marketplace.
     */
    @JsonGetter("products")
    public List<ProductEnum> getProducts ( ) { 
        return this.products;
    }
    
    /** SETTER
     * Products requested by marketplace.
     */
    @JsonSetter("products")
    public void setProducts (List<ProductEnum> value) { 
        this.products = value;
    }
 
}
