/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PayoutProductAdd 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3161164641709599082L;
    private List<ConsentRequest> consents;
    private String payoutInstrumentId;
    /** GETTER
     * An array of consents.
     */
    @JsonGetter("consents")
    public List<ConsentRequest> getConsents ( ) { 
        return this.consents;
    }
    
    /** SETTER
     * An array of consents.
     */
    @JsonSetter("consents")
    public void setConsents (List<ConsentRequest> value) { 
        this.consents = value;
    }
 
    /** GETTER
     * An unique id of Payout Instrument Resource
     */
    @JsonGetter("payoutInstrumentId")
    public String getPayoutInstrumentId ( ) { 
        return this.payoutInstrumentId;
    }
    
    /** SETTER
     * An unique id of Payout Instrument Resource
     */
    @JsonSetter("payoutInstrumentId")
    public void setPayoutInstrumentId (String value) { 
        this.payoutInstrumentId = value;
    }
 
}
