/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PayoutProductSubResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3472872960355909917L;
    private List<ConsentResource> consents;
    private StatusReasonResource status;
    private String payoutInstrumentId;
    private ActionStatusResource creditStatus;
    private ActionStatusResource debitStatus;
    /** GETTER
     * An array of consents.
     */
    @JsonGetter("consents")
    public List<ConsentResource> getConsents ( ) { 
        return this.consents;
    }
    
    /** SETTER
     * An array of consents.
     */
    @JsonSetter("consents")
    public void setConsents (List<ConsentResource> value) { 
        this.consents = value;
    }
 
    /** GETTER
     * The status and reason for the status of the entity.
     */
    @JsonGetter("status")
    public StatusReasonResource getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The status and reason for the status of the entity.
     */
    @JsonSetter("status")
    public void setStatus (StatusReasonResource value) { 
        this.status = value;
    }
 
    /** GETTER
     * payout instrumnet id
     */
    @JsonGetter("payoutInstrumentId")
    public String getPayoutInstrumentId ( ) { 
        return this.payoutInstrumentId;
    }
    
    /** SETTER
     * payout instrumnet id
     */
    @JsonSetter("payoutInstrumentId")
    public void setPayoutInstrumentId (String value) { 
        this.payoutInstrumentId = value;
    }
 
    /** GETTER
     * The status of the entity.
     */
    @JsonGetter("creditStatus")
    public ActionStatusResource getCreditStatus ( ) { 
        return this.creditStatus;
    }
    
    /** SETTER
     * The status of the entity.
     */
    @JsonSetter("creditStatus")
    public void setCreditStatus (ActionStatusResource value) { 
        this.creditStatus = value;
    }
 
    /** GETTER
     * The status of the entity.
     */
    @JsonGetter("debitStatus")
    public ActionStatusResource getDebitStatus ( ) { 
        return this.debitStatus;
    }
    
    /** SETTER
     * The status of the entity.
     */
    @JsonSetter("debitStatus")
    public void setDebitStatus (ActionStatusResource value) { 
        this.debitStatus = value;
    }
 
}
