/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class PayoutInstrumentResourceCommonEntitiesBuilder {
    //the instance to build
    private PayoutInstrumentResourceCommonEntities payoutInstrumentResourceCommonEntities;

    /**
     * Default constructor to initialize the instance
     */
    public PayoutInstrumentResourceCommonEntitiesBuilder() {
        payoutInstrumentResourceCommonEntities = new PayoutInstrumentResourceCommonEntities();
    }

    /**
     * The partners externalId id for the Payout Instrument.
     */
    public PayoutInstrumentResourceCommonEntitiesBuilder externalId(String externalId) {
        payoutInstrumentResourceCommonEntities.setExternalId(externalId);
        return this;
    }

    /**
     * The Bank account information.
     */
    public PayoutInstrumentResourceCommonEntitiesBuilder bankAccount(BankAccountResource bankAccount) {
        payoutInstrumentResourceCommonEntities.setBankAccount(bankAccount);
        return this;
    }

    /**
     * Payment card details.
     */
    public PayoutInstrumentResourceCommonEntitiesBuilder paymentCard(CardDataResource paymentCard) {
        payoutInstrumentResourceCommonEntities.setPaymentCard(paymentCard);
        return this;
    }

    /**
     * The type of finanancial instrument [BANK_ACCOUNT]
     */
    public PayoutInstrumentResourceCommonEntitiesBuilder type(Type2Enum type) {
        payoutInstrumentResourceCommonEntities.setType(type);
        return this;
    }

    /**
     * The entity manages the Instrument. It can be merchant or marketplace.
     */
    public PayoutInstrumentResourceCommonEntitiesBuilder managedBy(List<String> managedBy) {
        payoutInstrumentResourceCommonEntities.setManagedBy(managedBy);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PayoutInstrumentResourceCommonEntities build() {
        return payoutInstrumentResourceCommonEntities;
    }
}