/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class PayoutInstrumentRequestBuilder {
    //the instance to build
    private PayoutInstrumentRequest payoutInstrumentRequest;

    /**
     * Default constructor to initialize the instance
     */
    public PayoutInstrumentRequestBuilder() {
        payoutInstrumentRequest = new PayoutInstrumentRequest();
    }

    /**
     * The partners externalId id for the Payout Instrument.
     */
    public PayoutInstrumentRequestBuilder externalId(String externalId) {
        payoutInstrumentRequest.setExternalId(externalId);
        return this;
    }

    /**
     * The Bank account information.
     */
    public PayoutInstrumentRequestBuilder bankAccount(BankAccountResource bankAccount) {
        payoutInstrumentRequest.setBankAccount(bankAccount);
        return this;
    }

    /**
     * Payment card details.
     */
    public PayoutInstrumentRequestBuilder paymentCard(CardDataResource paymentCard) {
        payoutInstrumentRequest.setPaymentCard(paymentCard);
        return this;
    }

    /**
     * The type of finanancial instrument [BANK_ACCOUNT]
     */
    public PayoutInstrumentRequestBuilder type(Type2Enum type) {
        payoutInstrumentRequest.setType(type);
        return this;
    }

    /**
     * The entity manages the Instrument. It can be merchant or marketplace.
     */
    public PayoutInstrumentRequestBuilder managedBy(List<String> managedBy) {
        payoutInstrumentRequest.setManagedBy(managedBy);
        return this;
    }

    /**
     * The owner of the asset
     */
    public PayoutInstrumentRequestBuilder owner(OwnerResource owner) {
        payoutInstrumentRequest.setOwner(owner);
        return this;
    }

    /**
     * list of consent requests
     */
    public PayoutInstrumentRequestBuilder consents(List<Consent> consents) {
        payoutInstrumentRequest.setConsents(consents);
        return this;
    }

    /**
     * Products requested by marketplace.
     */
    public PayoutInstrumentRequestBuilder products(List<ProductEnum> products) {
        payoutInstrumentRequest.setProducts(products);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PayoutInstrumentRequest build() {
        return payoutInstrumentRequest;
    }
}