/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class PhoneResourceBuilder {
    //the instance to build
    private PhoneResource phoneResource;

    /**
     * Default constructor to initialize the instance
     */
    public PhoneResourceBuilder() {
        phoneResource = new PhoneResource();
    }

    /**
     * The phone number.
     */
    public PhoneResourceBuilder number(String number) {
        phoneResource.setNumber(number);
        return this;
    }

    /**
     * The phone extension.
     */
    public PhoneResourceBuilder extension(String extension) {
        phoneResource.setExtension(extension);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PhoneResource build() {
        return phoneResource;
    }
}