/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PriceSettingResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 3864788881485688946L;
    private MoneyResource minRate;
    private MoneyResource maxRate;
    private MoneyResource cleaningFee;
    private Boolean sameDayChargeAllowed;
    private Boolean autoPricing;
    private RentingFrequencyEnum rentingFrequency;
    private PaymentTermsEnum paymentTerms;
    /** GETTER
     * A money object defines the currency type and amount.
     */
    @JsonGetter("minRate")
    public MoneyResource getMinRate ( ) { 
        return this.minRate;
    }
    
    /** SETTER
     * A money object defines the currency type and amount.
     */
    @JsonSetter("minRate")
    public void setMinRate (MoneyResource value) { 
        this.minRate = value;
    }
 
    /** GETTER
     * A money object defines the currency type and amount.
     */
    @JsonGetter("maxRate")
    public MoneyResource getMaxRate ( ) { 
        return this.maxRate;
    }
    
    /** SETTER
     * A money object defines the currency type and amount.
     */
    @JsonSetter("maxRate")
    public void setMaxRate (MoneyResource value) { 
        this.maxRate = value;
    }
 
    /** GETTER
     * A money object defines the currency type and amount.
     */
    @JsonGetter("cleaningFee")
    public MoneyResource getCleaningFee ( ) { 
        return this.cleaningFee;
    }
    
    /** SETTER
     * A money object defines the currency type and amount.
     */
    @JsonSetter("cleaningFee")
    public void setCleaningFee (MoneyResource value) { 
        this.cleaningFee = value;
    }
 
    /** GETTER
     * Is there a same day charge for the property.
     */
    @JsonGetter("sameDayChargeAllowed")
    public Boolean getSameDayChargeAllowed ( ) { 
        return this.sameDayChargeAllowed;
    }
    
    /** SETTER
     * Is there a same day charge for the property.
     */
    @JsonSetter("sameDayChargeAllowed")
    public void setSameDayChargeAllowed (Boolean value) { 
        this.sameDayChargeAllowed = value;
    }
 
    /** GETTER
     * Is auto pricing setup for the property.
     */
    @JsonGetter("autoPricing")
    public Boolean getAutoPricing ( ) { 
        return this.autoPricing;
    }
    
    /** SETTER
     * Is auto pricing setup for the property.
     */
    @JsonSetter("autoPricing")
    public void setAutoPricing (Boolean value) { 
        this.autoPricing = value;
    }
 
    /** GETTER
     * The renting frequencey for the property.
     */
    @JsonGetter("rentingFrequency")
    public RentingFrequencyEnum getRentingFrequency ( ) { 
        return this.rentingFrequency;
    }
    
    /** SETTER
     * The renting frequencey for the property.
     */
    @JsonSetter("rentingFrequency")
    public void setRentingFrequency (RentingFrequencyEnum value) { 
        this.rentingFrequency = value;
    }
 
    /** GETTER
     * The terms of payment for the property for a traveler [single, multiple].
     */
    @JsonGetter("paymentTerms")
    public PaymentTermsEnum getPaymentTerms ( ) { 
        return this.paymentTerms;
    }
    
    /** SETTER
     * The terms of payment for the property for a traveler [single, multiple].
     */
    @JsonSetter("paymentTerms")
    public void setPaymentTerms (PaymentTermsEnum value) { 
        this.paymentTerms = value;
    }
 
}
