/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yapstone.apiuat.DateTimeHelper;
import org.joda.time.LocalDate;

@JsonInclude(Include.ALWAYS)
public class PrimaryContactResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2880332839539915658L;
    private NameResource name;
    private AddressResource address;
    private PhoneResource phone;
    private String email;
    private GovIdentificationResource govIdentification;
    private GenderEnum gender;
    private LocalDate dateOfBirth;
    private String countryOfBirth;
    private String nationality;
    private String websiteURL;
    /** GETTER
     * The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix.
     */
    @JsonGetter("name")
    public NameResource getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix.
     */
    @JsonSetter("name")
    public void setName (NameResource value) { 
        this.name = value;
    }
 
    /** GETTER
     * The address of the application, asset, bank, etc.
     */
    @JsonGetter("address")
    public AddressResource getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * The address of the application, asset, bank, etc.
     */
    @JsonSetter("address")
    public void setAddress (AddressResource value) { 
        this.address = value;
    }
 
    /** GETTER
     * The phone number.
     */
    @JsonGetter("phone")
    public PhoneResource getPhone ( ) { 
        return this.phone;
    }
    
    /** SETTER
     * The phone number.
     */
    @JsonSetter("phone")
    public void setPhone (PhoneResource value) { 
        this.phone = value;
    }
 
    /** GETTER
     * The email address.
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * The email address.
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
    /** GETTER
     * The goverment identification information.For US - Need Last4 SSN.
     */
    @JsonGetter("govIdentification")
    public GovIdentificationResource getGovIdentification ( ) { 
        return this.govIdentification;
    }
    
    /** SETTER
     * The goverment identification information.For US - Need Last4 SSN.
     */
    @JsonSetter("govIdentification")
    public void setGovIdentification (GovIdentificationResource value) { 
        this.govIdentification = value;
    }
 
    /** GETTER
     * The gender of the person. (M, F, O)
     */
    @JsonGetter("gender")
    public GenderEnum getGender ( ) { 
        return this.gender;
    }
    
    /** SETTER
     * The gender of the person. (M, F, O)
     */
    @JsonSetter("gender")
    public void setGender (GenderEnum value) { 
        this.gender = value;
    }
 
    /** GETTER
     * The date of birth for the person.
     */
    @JsonGetter("dateOfBirth")
    @JsonSerialize(using=DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getDateOfBirth ( ) { 
        return this.dateOfBirth;
    }
    
    /** SETTER
     * The date of birth for the person.
     */
    @JsonSetter("dateOfBirth")
    @JsonDeserialize(using=DateTimeHelper.SimpleDateDeserializer.class)
    public void setDateOfBirth (LocalDate value) { 
        this.dateOfBirth = value;
    }
 
    /** GETTER
     * The country of birth for the person.
     */
    @JsonGetter("countryOfBirth")
    public String getCountryOfBirth ( ) { 
        return this.countryOfBirth;
    }
    
    /** SETTER
     * The country of birth for the person.
     */
    @JsonSetter("countryOfBirth")
    public void setCountryOfBirth (String value) { 
        this.countryOfBirth = value;
    }
 
    /** GETTER
     * The nationality of the person.
     */
    @JsonGetter("nationality")
    public String getNationality ( ) { 
        return this.nationality;
    }
    
    /** SETTER
     * The nationality of the person.
     */
    @JsonSetter("nationality")
    public void setNationality (String value) { 
        this.nationality = value;
    }
 
    /** GETTER
     * The website hostname.
     */
    @JsonGetter("websiteURL")
    public String getWebsiteURL ( ) { 
        return this.websiteURL;
    }
    
    /** SETTER
     * The website hostname.
     */
    @JsonSetter("websiteURL")
    public void setWebsiteURL (String value) { 
        this.websiteURL = value;
    }
 
}
