/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.LocalDate;

public class PrimaryContactResourceBuilder {
    //the instance to build
    private PrimaryContactResource primaryContactResource;

    /**
     * Default constructor to initialize the instance
     */
    public PrimaryContactResourceBuilder() {
        primaryContactResource = new PrimaryContactResource();
    }

    /**
     * The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix.
     */
    public PrimaryContactResourceBuilder name(NameResource name) {
        primaryContactResource.setName(name);
        return this;
    }

    /**
     * The address of the application, asset, bank, etc.
     */
    public PrimaryContactResourceBuilder address(AddressResource address) {
        primaryContactResource.setAddress(address);
        return this;
    }

    /**
     * The phone number.
     */
    public PrimaryContactResourceBuilder phone(PhoneResource phone) {
        primaryContactResource.setPhone(phone);
        return this;
    }

    /**
     * The email address.
     */
    public PrimaryContactResourceBuilder email(String email) {
        primaryContactResource.setEmail(email);
        return this;
    }

    /**
     * The goverment identification information.For US - Need Last4 SSN.
     */
    public PrimaryContactResourceBuilder govIdentification(GovIdentificationResource govIdentification) {
        primaryContactResource.setGovIdentification(govIdentification);
        return this;
    }

    /**
     * The gender of the person. (M, F, O)
     */
    public PrimaryContactResourceBuilder gender(GenderEnum gender) {
        primaryContactResource.setGender(gender);
        return this;
    }

    /**
     * The date of birth for the person.
     */
    public PrimaryContactResourceBuilder dateOfBirth(LocalDate dateOfBirth) {
        primaryContactResource.setDateOfBirth(dateOfBirth);
        return this;
    }

    /**
     * The country of birth for the person.
     */
    public PrimaryContactResourceBuilder countryOfBirth(String countryOfBirth) {
        primaryContactResource.setCountryOfBirth(countryOfBirth);
        return this;
    }

    /**
     * The nationality of the person.
     */
    public PrimaryContactResourceBuilder nationality(String nationality) {
        primaryContactResource.setNationality(nationality);
        return this;
    }

    /**
     * The website hostname.
     */
    public PrimaryContactResourceBuilder websiteURL(String websiteURL) {
        primaryContactResource.setWebsiteURL(websiteURL);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PrimaryContactResource build() {
        return primaryContactResource;
    }
}