/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class ProCategoryResourceBuilder {
    //the instance to build
    private ProCategoryResource proCategoryResource;

    /**
     * Default constructor to initialize the instance
     */
    public ProCategoryResourceBuilder() {
        proCategoryResource = new ProCategoryResource();
    }

    /**
     * merchant category code of applicant.
     */
    public ProCategoryResourceBuilder code(int code) {
        proCategoryResource.setCode(code);
        return this;
    }

    /**
     * merchant category code description of applicant.
     */
    public ProCategoryResourceBuilder description(String description) {
        proCategoryResource.setDescription(description);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ProCategoryResource build() {
        return proCategoryResource;
    }
}