/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ProductRead 
        implements java.io.Serializable {
    private static final long serialVersionUID = 20710079669967799L;
    private List<ConsentResource> consents;
    /** GETTER
     * An array of consents.
     */
    @JsonGetter("consents")
    public List<ConsentResource> getConsents ( ) { 
        return this.consents;
    }
    
    /** SETTER
     * An array of consents.
     */
    @JsonSetter("consents")
    public void setConsents (List<ConsentResource> value) { 
        this.consents = value;
    }
 
}
