/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class ProductWriteBuilder {
    //the instance to build
    private ProductWrite productWrite;

    /**
     * Default constructor to initialize the instance
     */
    public ProductWriteBuilder() {
        productWrite = new ProductWrite();
    }

    /**
     * An array of consents.
     */
    public ProductWriteBuilder consents(List<ConsentRequest> consents) {
        productWrite.setConsents(consents);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ProductWrite build() {
        return productWrite;
    }
}