/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Products 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3627029425077357993L;
    private List<MarketplaceProductAdd> marketplaces;
    private List<PayoutProductAdd> payouts;
    /** GETTER
     * list of marketplace resources
     */
    @JsonGetter("marketplaces")
    public List<MarketplaceProductAdd> getMarketplaces ( ) { 
        return this.marketplaces;
    }
    
    /** SETTER
     * list of marketplace resources
     */
    @JsonSetter("marketplaces")
    public void setMarketplaces (List<MarketplaceProductAdd> value) { 
        this.marketplaces = value;
    }
 
    /** GETTER
     * list of payout resoucres
     */
    @JsonGetter("payouts")
    public List<PayoutProductAdd> getPayouts ( ) { 
        return this.payouts;
    }
    
    /** SETTER
     * list of payout resoucres
     */
    @JsonSetter("payouts")
    public void setPayouts (List<PayoutProductAdd> value) { 
        this.payouts = value;
    }
 
}
