/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PropertyInfoResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7807731691419970919L;
    private Integer capacity;
    private Integer bedroomCount;
    private Double bathroomCount;
    private List<String> amenities;
    /** GETTER
     * The capacity of the property.
     */
    @JsonGetter("capacity")
    public Integer getCapacity ( ) { 
        return this.capacity;
    }
    
    /** SETTER
     * The capacity of the property.
     */
    @JsonSetter("capacity")
    public void setCapacity (Integer value) { 
        this.capacity = value;
    }
 
    /** GETTER
     * The number of bedrooms.
     */
    @JsonGetter("bedroomCount")
    public Integer getBedroomCount ( ) { 
        return this.bedroomCount;
    }
    
    /** SETTER
     * The number of bedrooms.
     */
    @JsonSetter("bedroomCount")
    public void setBedroomCount (Integer value) { 
        this.bedroomCount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bathroomCount")
    public Double getBathroomCount ( ) { 
        return this.bathroomCount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bathroomCount")
    public void setBathroomCount (Double value) { 
        this.bathroomCount = value;
    }
 
    /** GETTER
     * List of amenitites the property has.
     */
    @JsonGetter("amenities")
    public List<String> getAmenities ( ) { 
        return this.amenities;
    }
    
    /** SETTER
     * List of amenitites the property has.
     */
    @JsonSetter("amenities")
    public void setAmenities (List<String> value) { 
        this.amenities = value;
    }
 
}
