/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.LocalDate;

public class PropertyHistoryResourceBuilder {
    //the instance to build
    private PropertyHistoryResource propertyHistoryResource;

    /**
     * Default constructor to initialize the instance
     */
    public PropertyHistoryResourceBuilder() {
        propertyHistoryResource = new PropertyHistoryResource();
    }

    /**
     * The date the property was active
     */
    public PropertyHistoryResourceBuilder activeSince(LocalDate activeSince) {
        propertyHistoryResource.setActiveSince(activeSince);
        return this;
    }

    /**
     * The number of charges.
     */
    public PropertyHistoryResourceBuilder chargeCount(Integer chargeCount) {
        propertyHistoryResource.setChargeCount(chargeCount);
        return this;
    }

    /**
     * The number of chargebacks.
     */
    public PropertyHistoryResourceBuilder chargebackCount(Integer chargebackCount) {
        propertyHistoryResource.setChargebackCount(chargebackCount);
        return this;
    }

    /**
     * A money object defines the currency type and amount.
     */
    public PropertyHistoryResourceBuilder chargeVolume(MoneyResource chargeVolume) {
        propertyHistoryResource.setChargeVolume(chargeVolume);
        return this;
    }

    /**
     * A money object defines the currency type and amount.
     */
    public PropertyHistoryResourceBuilder chargebackVolume(MoneyResource chargebackVolume) {
        propertyHistoryResource.setChargebackVolume(chargebackVolume);
        return this;
    }

    /**
     * Property stats and counts.
     */
    public PropertyHistoryResourceBuilder propertyTracker(PropertyTrackerResource propertyTracker) {
        propertyHistoryResource.setPropertyTracker(propertyTracker);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PropertyHistoryResource build() {
        return propertyHistoryResource;
    }
}