/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PropertyResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5329333327748921677L;
    private String name;
    private String displayName;
    private AddressResource address;
    private PropertyInfoResource propertyInfo;
    private PropertyHistoryResource propertyHistory;
    private MarketPlacePropertyResource mktPlaceInfo;
    /** GETTER
     * The name of the asset.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the asset.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The display name of the asset.
     */
    @JsonGetter("displayName")
    public String getDisplayName ( ) { 
        return this.displayName;
    }
    
    /** SETTER
     * The display name of the asset.
     */
    @JsonSetter("displayName")
    public void setDisplayName (String value) { 
        this.displayName = value;
    }
 
    /** GETTER
     * The address of the application, asset, bank, etc.
     */
    @JsonGetter("address")
    public AddressResource getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * The address of the application, asset, bank, etc.
     */
    @JsonSetter("address")
    public void setAddress (AddressResource value) { 
        this.address = value;
    }
 
    /** GETTER
     * Information about the property
     */
    @JsonGetter("propertyInfo")
    public PropertyInfoResource getPropertyInfo ( ) { 
        return this.propertyInfo;
    }
    
    /** SETTER
     * Information about the property
     */
    @JsonSetter("propertyInfo")
    public void setPropertyInfo (PropertyInfoResource value) { 
        this.propertyInfo = value;
    }
 
    /** GETTER
     * Historical information on the property.
     */
    @JsonGetter("propertyHistory")
    public PropertyHistoryResource getPropertyHistory ( ) { 
        return this.propertyHistory;
    }
    
    /** SETTER
     * Historical information on the property.
     */
    @JsonSetter("propertyHistory")
    public void setPropertyHistory (PropertyHistoryResource value) { 
        this.propertyHistory = value;
    }
 
    /** GETTER
     * Market place information about the property, includes reservation settings, check in/out time, etc.
     */
    @JsonGetter("mktPlaceInfo")
    public MarketPlacePropertyResource getMktPlaceInfo ( ) { 
        return this.mktPlaceInfo;
    }
    
    /** SETTER
     * Market place information about the property, includes reservation settings, check in/out time, etc.
     */
    @JsonSetter("mktPlaceInfo")
    public void setMktPlaceInfo (MarketPlacePropertyResource value) { 
        this.mktPlaceInfo = value;
    }
 
}
