/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class PropertyResourceBuilder {
    //the instance to build
    private PropertyResource propertyResource;

    /**
     * Default constructor to initialize the instance
     */
    public PropertyResourceBuilder() {
        propertyResource = new PropertyResource();
    }

    /**
     * The name of the asset.
     */
    public PropertyResourceBuilder name(String name) {
        propertyResource.setName(name);
        return this;
    }

    /**
     * The display name of the asset.
     */
    public PropertyResourceBuilder displayName(String displayName) {
        propertyResource.setDisplayName(displayName);
        return this;
    }

    /**
     * The address of the application, asset, bank, etc.
     */
    public PropertyResourceBuilder address(AddressResource address) {
        propertyResource.setAddress(address);
        return this;
    }

    /**
     * Information about the property
     */
    public PropertyResourceBuilder propertyInfo(PropertyInfoResource propertyInfo) {
        propertyResource.setPropertyInfo(propertyInfo);
        return this;
    }

    /**
     * Historical information on the property.
     */
    public PropertyResourceBuilder propertyHistory(PropertyHistoryResource propertyHistory) {
        propertyResource.setPropertyHistory(propertyHistory);
        return this;
    }

    /**
     * Market place information about the property, includes reservation settings, check in/out time, etc.
     */
    public PropertyResourceBuilder mktPlaceInfo(MarketPlacePropertyResource mktPlaceInfo) {
        propertyResource.setMktPlaceInfo(mktPlaceInfo);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PropertyResource build() {
        return propertyResource;
    }
}