/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PropertyTrackerResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1349524553316027605L;
    private Integer inquiryCount;
    private Integer ratingCount;
    private Integer complaintCount;
    private Double rating;
    /** GETTER
     * The number of inquries.
     */
    @JsonGetter("inquiryCount")
    public Integer getInquiryCount ( ) { 
        return this.inquiryCount;
    }
    
    /** SETTER
     * The number of inquries.
     */
    @JsonSetter("inquiryCount")
    public void setInquiryCount (Integer value) { 
        this.inquiryCount = value;
    }
 
    /** GETTER
     * The number of ratings.
     */
    @JsonGetter("ratingCount")
    public Integer getRatingCount ( ) { 
        return this.ratingCount;
    }
    
    /** SETTER
     * The number of ratings.
     */
    @JsonSetter("ratingCount")
    public void setRatingCount (Integer value) { 
        this.ratingCount = value;
    }
 
    /** GETTER
     * The number of complaints made on the property.
     */
    @JsonGetter("complaintCount")
    public Integer getComplaintCount ( ) { 
        return this.complaintCount;
    }
    
    /** SETTER
     * The number of complaints made on the property.
     */
    @JsonSetter("complaintCount")
    public void setComplaintCount (Integer value) { 
        this.complaintCount = value;
    }
 
    /** GETTER
     * The rating of the property.
     */
    @JsonGetter("rating")
    public Double getRating ( ) { 
        return this.rating;
    }
    
    /** SETTER
     * The rating of the property.
     */
    @JsonSetter("rating")
    public void setRating (Double value) { 
        this.rating = value;
    }
 
}
