/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.LocalDate;

public class RegistrationResourceBuilder {
    //the instance to build
    private RegistrationResource registrationResource;

    /**
     * Default constructor to initialize the instance
     */
    public RegistrationResourceBuilder() {
        registrationResource = new RegistrationResource();
    }

    /**
     * Date of the company was created.
     */
    public RegistrationResourceBuilder formationDate(LocalDate formationDate) {
        registrationResource.setFormationDate(formationDate);
        return this;
    }

    /**
     * The country where the business was created.
     */
    public RegistrationResourceBuilder formationCountry(String formationCountry) {
        registrationResource.setFormationCountry(formationCountry);
        return this;
    }

    /**
     * The US state where the business was created or province
     */
    public RegistrationResourceBuilder formationState(String formationState) {
        registrationResource.setFormationState(formationState);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RegistrationResource build() {
        return registrationResource;
    }
}