/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ReservationSettingResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6551694831582920630L;
    private StaySettingResource staySetting;
    private PriceSettingResource priceSetting;
    /** GETTER
     * The stay settings includes min/max number of days that the property can be reserved.
     */
    @JsonGetter("staySetting")
    public StaySettingResource getStaySetting ( ) { 
        return this.staySetting;
    }
    
    /** SETTER
     * The stay settings includes min/max number of days that the property can be reserved.
     */
    @JsonSetter("staySetting")
    public void setStaySetting (StaySettingResource value) { 
        this.staySetting = value;
    }
 
    /** GETTER
     * Information about the properties price settings including min/max rate, and different fees.
     */
    @JsonGetter("priceSetting")
    public PriceSettingResource getPriceSetting ( ) { 
        return this.priceSetting;
    }
    
    /** SETTER
     * Information about the properties price settings including min/max rate, and different fees.
     */
    @JsonSetter("priceSetting")
    public void setPriceSetting (PriceSettingResource value) { 
        this.priceSetting = value;
    }
 
}
