/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonTypeInfo(
          use = JsonTypeInfo.Id.NAME,
          include = JsonTypeInfo.As.EXISTING_PROPERTY,
          property = "restResponse",
          defaultImpl = RestResponse.class,
          visible = true)
@JsonSubTypes({
    @Type(value = OfferingResponse.class, name = "OfferingResponse")
})
@JsonInclude(Include.ALWAYS)
public class RestResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1265500869036480206L;
    private MetaPage meta;
    private String restResponse;
    /** GETTER
     * Response metadata
     */
    @JsonGetter("_meta")
    public MetaPage getMeta ( ) { 
        return this.meta;
    }
    
    /** SETTER
     * Response metadata
     */
    @JsonSetter("_meta")
    public void setMeta (MetaPage value) { 
        this.meta = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("restResponse")
    public String getRestResponse ( ) { 
        return this.restResponse;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("restResponse")
    public void setRestResponse (String value) { 
        this.restResponse = value;
    }
 
}
