/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class SocialNetworkResourceBuilder {
    //the instance to build
    private SocialNetworkResource socialNetworkResource;

    /**
     * Default constructor to initialize the instance
     */
    public SocialNetworkResourceBuilder() {
        socialNetworkResource = new SocialNetworkResource();
    }

    /**
     * The type of social network [FACEBOOK, TWITTER, GOOGLE_PLUS, LINKEDIN, PINTEREST, INSTAGRAM, SNAPCHAT]
     */
    public SocialNetworkResourceBuilder network(NetworkEnum network) {
        socialNetworkResource.setNetwork(network);
        return this;
    }

    /**
     * The account networkId that is used for the social network to identify the user.
     */
    public SocialNetworkResourceBuilder networkId(String networkId) {
        socialNetworkResource.setNetworkId(networkId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SocialNetworkResource build() {
        return socialNetworkResource;
    }
}