/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class StatusReasonResourceBuilder {
    //the instance to build
    private StatusReasonResource statusReasonResource;

    /**
     * Default constructor to initialize the instance
     */
    public StatusReasonResourceBuilder() {
        statusReasonResource = new StatusReasonResource();
    }

    /**
     * The status of the entity.
     */
    public StatusReasonResourceBuilder status(Status1Enum status) {
        statusReasonResource.setStatus(status);
        return this;
    }

    /**
     * Reasoncode for status change.
     */
    public StatusReasonResourceBuilder disabledReason(String disabledReason) {
        statusReasonResource.setDisabledReason(disabledReason);
        return this;
    }

    public StatusReasonResourceBuilder disabledReasonNotes(String disabledReasonNotes) {
        statusReasonResource.setDisabledReasonNotes(disabledReasonNotes);
        return this;
    }

    public StatusReasonResourceBuilder declinedReasons(List<String> declinedReasons) {
        statusReasonResource.setDeclinedReasons(declinedReasons);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StatusReasonResource build() {
        return statusReasonResource;
    }
}