/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class StatusReasonResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1318419040945826570L;
    private Status1Enum status;
    private String disabledReason;
    private String disabledReasonNotes;
    private List<String> declinedReasons;
    /** GETTER
     * The status of the entity.
     */
    @JsonGetter("status")
    public Status1Enum getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The status of the entity.
     */
    @JsonSetter("status")
    public void setStatus (Status1Enum value) { 
        this.status = value;
    }
 
    /** GETTER
     * Reasoncode for status change.
     */
    @JsonGetter("disabledReason")
    public String getDisabledReason ( ) { 
        return this.disabledReason;
    }
    
    /** SETTER
     * Reasoncode for status change.
     */
    @JsonSetter("disabledReason")
    public void setDisabledReason (String value) { 
        this.disabledReason = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("disabledReasonNotes")
    public String getDisabledReasonNotes ( ) { 
        return this.disabledReasonNotes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("disabledReasonNotes")
    public void setDisabledReasonNotes (String value) { 
        this.disabledReasonNotes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("declinedReasons")
    public List<String> getDeclinedReasons ( ) { 
        return this.declinedReasons;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("declinedReasons")
    public void setDeclinedReasons (List<String> value) { 
        this.declinedReasons = value;
    }
 
}
