/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class SuspensionReasonResource 
        implements java.io.Serializable {
    private static final long serialVersionUID = 69040064838291547L;
    private String suspensionReason;
    /** GETTER
     * reason for suspension if selected
     */
    @JsonGetter("suspensionReason")
    public String getSuspensionReason ( ) { 
        return this.suspensionReason;
    }
    
    /** SETTER
     * reason for suspension if selected
     */
    @JsonSetter("suspensionReason")
    public void setSuspensionReason (String value) { 
        this.suspensionReason = value;
    }
 
}
