/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;

public class SuspensionReasonResourceBuilder {
    //the instance to build
    private SuspensionReasonResource suspensionReasonResource;

    /**
     * Default constructor to initialize the instance
     */
    public SuspensionReasonResourceBuilder() {
        suspensionReasonResource = new SuspensionReasonResource();
    }

    /**
     * reason for suspension if selected
     */
    public SuspensionReasonResourceBuilder suspensionReason(String suspensionReason) {
        suspensionReasonResource.setSuspensionReason(suspensionReason);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SuspensionReasonResource build() {
        return suspensionReasonResource;
    }
}