/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.models;

import java.util.*;
import org.joda.time.LocalDate;

public class TravelerResourceBuilder {
    //the instance to build
    private TravelerResource travelerResource;

    /**
     * Default constructor to initialize the instance
     */
    public TravelerResourceBuilder() {
        travelerResource = new TravelerResource();
    }

    /**
     * The date the customer started as a traveler.
     */
    public TravelerResourceBuilder startedOn(LocalDate startedOn) {
        travelerResource.setStartedOn(startedOn);
        return this;
    }

    /**
     * The number of inquries.
     */
    public TravelerResourceBuilder inquiryCount(Integer inquiryCount) {
        travelerResource.setInquiryCount(inquiryCount);
        return this;
    }

    /**
     * The number of charges.
     */
    public TravelerResourceBuilder chargeCount(Integer chargeCount) {
        travelerResource.setChargeCount(chargeCount);
        return this;
    }

    /**
     * The number of ratings.
     */
    public TravelerResourceBuilder ratingCount(Integer ratingCount) {
        travelerResource.setRatingCount(ratingCount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TravelerResource build() {
        return travelerResource;
    }
}