/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.yapstone.apiuat.http.client.HttpContext;
import com.yapstone.apiuat.models.*;

public class CustomerErrorsException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = -30075456037126429L;
    private List<CustomerErrors1> customerErrors;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customerErrors")
    public List<CustomerErrors1> getCustomerErrors ( ) { 
        return this.customerErrors;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customerErrors")
    private void setCustomerErrors (List<CustomerErrors1> value) { 
        this.customerErrors = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public CustomerErrorsException(String reason, HttpContext context) {
        super(reason, context);
    }
}
