/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.yapstone.apiuat;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api-uat.yapstone.com/v2/onboarding";

    //TODO: Replace the authorization with an appropriate value
    public static String authorization = "";

}
